import { all } from "redux-saga/effects";

import {
  watchuploadImageCouponWorker,
  watchuploadImageRideTypeWorker,
} from "./imageUploadSaga";

import {
  watchLoginWorker,
  watchLogoutWorker,
  watchresetAdminPasswordWorker,
  watchResetLogoutAdminPasswordWorker,
} from "./authSaga";

import {
  watchAddAdminWorker,
  watchAdminFindOneWorker,
  watchAdminListWorker,
  watchBlockAdminListWorker,
  watchBlockAdminWorker,
  watchblockedDropdownListWorker,
  watchBlockedEditAdminWorker,
  watchDeleteAdminWorker,
  watchDeletedAdminListWorker,
  watchdeletedDropdownListWorker,
  watchDropdownListWorker,
  watchEditAdminWorker,
  watchUnblockAdminWorker,
} from "./manageAdminsSaga";

import {
  watchactivateRiderWorker,
  watchBlockedRiderDropDownListWorker,
  watchBlockedRiderHistoryViewWorker,
  watchblockedRiderListWorker,
  watchblockedRiderViewWorker,
  watchblockRiderWorker,
  watchDeletedRiderHistoryViewWorker,
  watchDeletedRiderListWorker,
  watchDeletedRiderViewWorker,
  watchdeleteRiderWorker,
  watchdelRiderDropDownListWorker,
  watchperDelRiderDropDownListWorker,
  watchpermanentDelRiderListWorker,
  watchpermanentDelRiderViewWorker,
  watchPermanentlyDeleteRiderWorker,
  watchresetRiderPictureWorker,
  watchresetRiderRatingWorker,
  watchRestoreRiderViewWorker,
  watchRiderDropDownListWorker,
  watchRiderHistoryViewWorker,
  watchRiderListWorker,
  watchRiderViewWorker,
  watchUnblockRiderViewWorker,
} from "./manageRidersSaga";

import {
  watchpendinfRefundUpdateWorker,
  watchpendinfRefundViewWorker,
  watchpendingRefundListWorker,
  watchpendRefundDropdownListWorker,
} from "./pendingRefundSaga";

import {
  watchsucessfulRefundListWorker,
  watchsucessfulRefundViewWorker,
  watchsucessRefundDropdownListWorker,
} from "./successFulRefundSaga";
import {
  watchcancelledRefundListWorker,
  watchcancelledRefundViewWorker,
  watchCancelRefundDropdownListWorker,
} from "./cancelledRefundSaga";
import {
  watchaddRideTypeWorker,
  watchrideTypeListWorker,
  watchrideTypeUpdateWorker,
  watchrideTypeViewWorker,
  watchrideTypeZoneListWorker,
  watchrideTypeDropDownListWorker,
  watchdeleteRideTypeWorker,
} from "./rideTypeSaga";
import {
  watchaddVehicleTypeWorker,
  watchrideTypeDropdownWorker,
  watchvehicleTypeListWorker,
  watchvehicleTypeUpdateWorker,
  watchvehicleTypeViewWorker,
  watchvehicleTypeDropDownListWorker,
} from "./vehicleTypeSaga";
import {
  watchongoingRequestIndividualWorker,
  watchongoingRequestListWorker,
  watchunSuccessfulRequestIndividualWorker,
  watchunSuccessfulRequestListWorker,
  watchOngoingDropDownListWorker,
  watchUnsuccessfulDropDownListWorker,
} from "./bookingRequestSaga";
import {
  watchongoingAccidentReportWorker,
  watchongoingBookingIndividualWorker,
  watchongoingBookingListWorker,
  watchongoingDriverReqCancelWorker,
  watchongoingEndTripWorker,
  watchongoingRiderReqCancelWorker,
  watchongoingUpdateBillingDetailsWorker,
  watchongoingUpdateFinalOdometerWorker,
  watchongoingUpdateInitialOdometerWorker,
  watchongoingUpdatePaymentMethodWorker,
  watchOngoingBookingsDropDownListWorker,
} from "./manageBookingSaga/onGoingBookingSaga";
import {
  watchcompletedBookingCancelDriverFineWorker,
  watchcompletedBookingCancelRefundWorker,
  watchcompletedBookingCreateRefundWorker,
  watchcompletedBookingIndividualWorker,
  watchcompletedBookingListWorker,
  watchcompletedUpdateBillingDetailsWorker,
  watchcompletedUpdateFinalOdometerWorker,
  watchcompletedUpdateInitialOdometerWorker,
  watchcompletedUpdatePaymentMethodWorker,
  watchCompletedBookingsDropDownListWorker,
} from "./manageBookingSaga/completedBookingSaga";
import {
  watchcancelledBookingCancelDriverFineWorker,
  watchcancelledBookingCancelRefundWorker,
  watchcancelledBookingCreateRefundWorker,
  watchcancelledBookingIndividualWorker,
  watchcancelledBookingListWorker,
  watchcancelledBookingUpdateBillingWorker,
  watchcancelledUpdateFinalOdometerWorker,
  watchcancelledUpdateInitialOdometerWorker,
  watchcancelledUpdatePaymentMethodWorker,
  watchCancelledBookingsDropDownListWorker,
} from "./manageBookingSaga/cancelledBookingSaga";
import {
  watchaccidentBookingCancelDriverFineWorker,
  watchaccidentBookingCancelRefundWorker,
  watchaccidentBookingCreateRefundWorker,
  watchaccidentBookingIndividualWorker,
  watchaccidentBookingListWorker,
  watchaccidentBookingUpdateBillingsWorker,
  watchaccidentUpdateFinalOdometerWorker,
  watchaccidentUpdateInitialOdometerWorker,
  watchaccidentUpdatePaymentMethodWorker,
  watchAccidentBookingsDropDownListWorker,
} from "./manageBookingSaga/accidentBookingSaga";
import {
  watchadjustedBookingIndividualWorker,
  watchadjustedBookingListWorker,
  watchadjustedBookingsDropDownListWorker,
} from "./manageBookingSaga/adjustedBookingSaga";
import {
  watchtripInvoiceDropDownListWorker,
  watchtripInvoiceListWorker,
  watchtripInvoiceWorker,
} from "./invoiceSaga";

import {
  watchactiveCouponAllViewWorker,
  watchcouponLocalZoneListWorkerWorker,
  watchcouponMainZoneListApiWorker,
  watchcouponOustationZoneListWorkerWorker,
  watchcouponSpecialZoneListWorkerWorker,
  watchcreateBookingDestinationWorker,
  watchcreateBookingDistanceWorker,
  watchcreateGeneralWorker,
  watchcreateNewAccountLifeSpanWorker,
  watchcreateNewAccountWorker,
  watchcreateOutstationPackageWorker,
  watchcreatePaymentMethodWorker,
  watchcreatePickupDropoffWorker,
  watchcreateRentalPackageWorker,
  watchdeletedCouponAllViewWorker,
  watchexpiredCouponAllViewWorker,
  watchpendingCouponAllViewWorker,
  watchrejectedCouponAllViewWorker,
} from "./riderCoupon/createCouponSaga";
import {
  watchactiveCouponSendReviewWorker,
  watchsendReviewWorker,
} from "./riderCoupon/sendReviewSaga";
import {
  watchactiveCouponEditWorker,
  watchactiveCouponFindOneWorker,
  watchbookingDestinationCouponEditWorker,
  watchbookingDistanceCouponEditWorker,
  watchdeletedCouponFindOneWorker,
  watchexpiredCouponFindOneWorker,
  watchgeneralCouponEditWorker,
  watchnewAccountCouponEditWorker,
  watchnewAccountLifeSpanCouponEditWorker,
  watchoutStationPackageCouponEditWorker,
  watchpaymentMethodCouponEditWorker,
  watchpendingCouponFindOneWorker,
  watchpickUpDropOffCouponEditWorker,
  watchrejectedCouponFindOneWorker,
  watchrentalPackageCouponEditWorker,
} from "./riderCoupon/findOneAndEditSaga";
import { watchapproveCouponWorker } from "./riderCoupon/approveCouponSaga";
import { watchrejectCouponWorker } from "./riderCoupon/rejectCouponSaga";
import { watchdeleteCouponWorker } from "./riderCoupon/deleteCouponSaga";
import {
  watchcouponUsageHistoryAllViewWorker,
  watchcouponUsageHistoryFindOneWorker,
} from "./riderCoupon/couponUsageSaga";

import {
  createDriverToDriverReferralWatcher,
  createDriverToRiderReferralWatcher,
  watchcreateReferralWorker,
} from "./referrals/createReferralSaga";
import {
  watchsendReviewDriverReferralWorker,
  watchsendReviewReferralWorker,
} from "./referrals/sendReviewReferralSaga";

import {
  watchactiveDriverCouponBroadcastEditWorker,
  watchactiveDriverCouponEditWorker,
  watchactiveDriverCouponListWorker,
  watchactiveDriverCouponWorker,
  watchapproveDriverCouponWorker,
  watchcreateDriverCouponBroadcastWorker,
  watchcreateDriverCouponWorker,
  watchdeletedDriverCouponListWorker,
  watchdeletedDriverCouponWorker,
  watchdeleteDriverCouponWorker,
  watchdropDownListDriverCouponActiveWorker,
  watchdropDownListDriverCouponDeletedWorker,
  watchdropDownListDriverCouponExpiredWorker,
  watchdropDownListDriverCouponRejectedWorker,
  watchdropDownListDriverCouponUsageWorker,
  watchdropDownListDriverCouponWorker,
  watchexpiredDriverCouponListWorker,
  watchexpiredDriverCouponWorker,
  watchrejectDriverCouponWorker,
  watchrejectedDriverCouponListWorker,
  watchrejectedDriverCouponWorker,
  watchreviewReqDriverCouponEditWorker,
  watchreviewReqDriverCouponListWorker,
  watchreviewReqDriverCouponWorker,
  watchusageHistoryDriverCouponListWorker,
  watchusageHistoryDriverCouponWorker,
} from "./driverCouponSaga";
import {
  watchreviewDriverRefD_To_DEditWorker,
  watchreviewDriverRefD_To_REditWorker,
  watchreviewReqDriverRefBroadcastEditWorker,
  watchReviewReqDriverRefListWorker,
  watchreviewReqDriverRefWorker,
  watchreviewReqReferralBroadcastEditWorker,
  watchreviewReqReferralEditWorker,
  watchreviewRequiredReferralAllViewWorker,
  watchreviewRequiredReferralFindOneWorker,
} from "./referrals/reviewRequiredSaga";
import {
  WatchactiveDriverRefBroadcastEditWorker,
  WatchactiveDriverRefEditWorker,
  watchactiveDriverRefFindOneWorker,
  watchactiveDriverRefListWorker,
  watchactiveReferralAllViewWorker,
  WatchactiveReferralBroadcastEditWorker,
  WatchactiveReferralEditWorker,
  watchactiveReferralFindOneWorker,
  watchapproveDriverRefWorker,
  watchapproveReferralWorker,
} from "./referrals/approveReferralSaga";
import {
  watchrejectDriverRefWorker,
  watchrejectedDriverRefListWorker,
  watchrejectedDriverRefWorker,
  watchrejectedReferralAllViewWorker,
  watchrejectedReferralFindOneWorker,
  watchrejectReferralWorker,
} from "./referrals/rejectReferralSaga";
import {
  watchdelDriverRefListWorker,
  watchdeletedDriverRefWorker,
  watchdeletedReferralAllViewWorker,
  watchdeletedReferralFindOneWorker,
  watchdeleteDriverRefWorker,
  watchdeleteReferralWorker,
} from "./referrals/deleteReferralSaga";
import {
  watchexpiredDriverRefIdListWorker,
  watchexpiredDriverRefIdWorker,
  watchexpiredReferralAllViewWorker,
  watchexpiredReferralFindOneWorker,
} from "./referrals/expiredReferralSaga";
import {
  WatchDriverRefSenderusageHistoryListWorker,
  WatchDriverRefSenderUsageHistoryWorker,
  WatchriderRefSenderFindAllusageHistoryWorker,
  WatchriderRefSenderFindOneUsageHistoryWorker,
} from "./referrals/senderHistorySaga";
import {
  WatchDriverRefReceiverUsageHistoryListWorker,
  WatchDriverRefReceiverUsageHistoryWorker,
  WatchriderRefReceiverFindAllusageHisWorker,
  WatchriderRefReceiverFindOneUsageHisWorker,
} from "./referrals/receiverHistorySaga";
import {
  watchAssignToAdminListWorker,
  watchDriverComplaintAssignWorker,
  watchDriverComplaintInitiateWorker,
  watchdriverComplPendingDropDownWorker,
  watchDriverPendComplaintsListWorker,
  watchDriverPendComplaintWorker,
  watchRiderComplaintAssignWorker,
  watchRiderComplaintInitiateWorker,
  watchriderComplPendingDropDownWorker,
  watchRiderPendComplaintsListWorker,
  watchRiderPendComplaintWorker,
} from "./complaints/pendingComplaintsSaga";
import {
  watchbookingIDListWorker,
  watchdriverComplInprogressDropDownWorker,
  watchdriverInProgComplaintReAssignWorker,
  watchDriverInprogressComplaintsListWorker,
  watchDriverInprogressComplaintWorker,
  watchriderComplInprogressDropDownWorker,
  watchriderInProgComplaintReAssignWorker,
  watchRiderInprogressComplaintsListWorker,
  watchRiderInprogressComplaintWorker,
} from "./complaints/inprogressComplaintsSaga";
import {
  watchdriverComplReslovedDropDownWorker,
  watchDriverResClosedComplaintWorker,
  watchDriverResolvedClosedComplaintsListWorker,
  watchriderComplReslovedDropDownWorker,
  watchRiderResClosedComplaintWorker,
  watchRiderResolvedClosedComplaintsListWorker,
} from "./complaints/resolvedAndClosedSaga";
import {
  watchaddLocalResponderWorker,
  watchLocalResponderConatctListWorker,
  watchLocalResponderDeleteWorker,
  watchLocalResponderListWorker,
  watchLocalResponderUpdateWorker,
  watchLocalResponderWorker,
} from "./sos/localResponderSaga";
import {
  watchassignSosToAdminListWorker,
  watchDriverPendSOSListWorker,
  watchDriverPendSOSWorker,
  watchDriverSOSAssignWorker,
  watchDriverSOSInitiateWorker,
  watchdriverSOSPendingDropDownWorker,
  watchgenerateSosCallDriverWorker,
  watchgenerateSosCallRiderWorker,
  watchRiderPendSOSListWorker,
  watchRiderPendSOSWorker,
  watchRiderSOSAssignWorker,
  watchRiderSOSInitiateWorker,
  watchriderSOSPendingDropDownWorker,
} from "./sos/pendingSosSaga";
import {
  watchdriverIDListApiWorker,
  watchDriverInprogressSOSListWorker,
  watchDriverInprogressSOSWorker,
  watchdriverInProgSOSReAssignWorker,
  watchdriverSOSInprogressDropDownWorker,
  watchriderIDListApiWorker,
  watchRiderInprogressSOSListWorker,
  watchRiderInprogressSOSWorker,
  watchriderInProgSOSReAssignWorker,
  watchriderSOSInprogressDropDownWorker,
} from "./sos/inprogressSosSaga";
import {
  watchDriverResClosedSOSWorker,
  watchDriverResolvedClosedSOSListWorker,
  watchRiderResClosedSOSWorker,
  watchRiderResolvedClosedSOSListWorker,
} from "./sos/resolvedAndClosedSosSaga";
import {
  watchcallComplaintDescriptionWorker,
  watchgenerateComplaintDriverWorker,
  watchgenerateComplaintRiderWorker,
} from "./complaints/callSaga";
import {
  WatchclearDriverReferralWorker,
  WatchclearRiderReferralWorker,
} from "./referrals/clearRefrralSaga";
import {
  WatchclearDriverCouponWorker,
  WatchclearRiderCouponWorker,
} from "./riderCoupon/clearCouponSaga";
import {
  watchCloseDriverCompliantWorker,
  watchCloseRiderCompliantWorker,
  watchforwardDriverComplaintWorker,
  watchforwardRiderComplaintWorker,
  watchmyComplaintsListWorker,
  watchmyComplaintsRiderListWorker,
  watchresolveDriverComplaintWorker,
  watchresolveRiderComplaintWorker,
} from "./complaints/myComplaintsSaga";
import {
  watchcreateDriverIncentiveWorker,
  watchDriIncentiveRevreqDrpdwnWorker,
  watchdriverIncentivePendingEditWorker,
  watchdriverIncentivePendingListWorker,
  watchdriverIncentivePendingWorker,
} from "./incentives/pendingIncentivesSaga";
import {
  watchApproveDriverIncentiveWorker,
  watchDriIncentiveActiveDrpdwnWorker,
  watchdriverIncentiveActiveCampaignEditWorker,
  watchdriverIncentiveActiveEditWorker,
  watchdriverIncentiveActiveListWorker,
  watchdriverIncentiveActiveWorker,
} from "./incentives/activeIncentivesSaga";
import {
  watchDriIncentiveRejectDrpdwnWorker,
  watchdriverIncentiveRejectedListWorker,
  watchdriverIncentiveRejectedWorker,
  watchrejcectDriverIncentiveWorker,
} from "./incentives/rejectedIncentivesSaga";
import {
  watchdeleteDriverIncentiveWorker,
  watchDriIncentiveDeleteDrpdwnWorker,
  watchdriverIncentiveDeletedListWorker,
  watchdriverIncentiveDeletedWorker,
} from "./incentives/deletedIncentivesSaga";
import {
  watchDriIncentiveExpireDrpdwnWorker,
  watchdriverIncentiveExpiredListWorker,
  watchdriverIncentiveExpiredWorker,
} from "./incentives/expiredIncentivesSaga";
import {
  watchDriIncentiveUdghisDrpdwnWorker,
  watchdriverIncentiveUseageHisListWorker,
  watchdriverIncentiveUseageHisWorker,
} from "./incentives/useageHisIncentivesSaga";
import {
  watchcouponRideTypeListWorker,
  watchdropDownListRiderCouponActiveWorker,
  watchdropDownListRiderCouponDeletedWorker,
  watchdropDownListRiderCouponExpiredWorker,
  watchdropDownListRiderCouponRejectedWorker,
  watchdropDownListRiderCouponUsageWorker,
  watchdropDownListRiderCouponWorker,
} from "./riderCoupon/dropdownListSaga";
import {
  watchdropDownListDriverReferralActiveWorker,
  watchdropDownListDriverReferralDeletedWorker,
  watchdropDownListDriverReferralExpiredWorker,
  watchdropDownListDriverReferralRejectedWorker,
  watchdropDownListDriverReferralUsageWorker,
  watchdropDownListDriverReferralWorker,
  watchdropDownListRiderReferralActiveWorker,
  watchdropDownListRiderReferralDeletedWorker,
  watchdropDownListRiderReferralExpiredWorker,
  watchdropDownListRiderReferralRejectedWorker,
  watchdropDownListRiderReferralUsageWorker,
  watchdropDownListRiderReferralWorker,
  watchreferralRideTypeListWorker,
} from "./referrals/dropdownListSaga";
import {
  watchDriBroadcastRevreqDrpdwnWorker,
  watchdriverBroadCastApproveWorker,
  watchdriverBroadCastCreateWorker,
  watchdriverBroadCastPendingListWorker,
  watchdriverBroadCastRejectWorker,
  watchreviewReqDriverBroadCastEditWorker,
  watchreviewReqDriverBroadCastWorker,
  watchreviewReqRiderBroadCastEditWorker,
  watchreviewReqRiderBroadCastWorker,
  watchRideBroadcastRevreqDrpdwnWorker,
  watchriderBroadCastApproveWorker,
  watchriderBroadCastCreateWorker,
  watchriderBroadCastPendingListWorker,
  watchriderBroadCastRejectWorker,
  watchrideTypeBroadcastDropdownWorker,
} from "./broadcast/pendandCreateBroadcastSaga";
import {
  watchActiveDriverBroadCastEditWorker,
  watchactivedriverBroadCastFindOneWorker,
  watchActiveRiderBroadCastEditWorker,
  watchactiveRiderBroadCastFindOneWorker,
  watchDriBroadcastActiveDrpdwnWorker,
  watchdriverBroadCastActiveListWorker,
  watchRideBroadcastActiveDrpdwnWorker,
  watchriderBroadCastActiveListWorker,
} from "./broadcast/activeBroadcastSaga";
import {
  watchDriBroadcastRejectDrpdwnWorker,
  watchdriverBroadCastRejectFindOneWorker,
  watchdriverBroadCastRejectListWorker,
  watchRideBroadcastRejectDrpdwnWorker,
  watchriderBroadCastRejectFindOneWorker,
  watchriderBroadCastRejectListWorker,
} from "./broadcast/rejectBroadcastSaga";
import {
  watchDriBroadcastDeleteDrpdwnWorker,
  watchdriverBroadCastDeleteFindOneWorker,
  watchdriverBroadCastDeleteListWorker,
  watchdriverBroadCastDeleteWorker,
  watchRideBroadcastDeleteDrpdwnWorker,
  watchriderBroadCastDeleteFindOneWorker,
  watchriderBroadCastDeleteListWorker,
  watchriderBroadCastDeleteWorker,
} from "./broadcast/deleteBroadcastSaga";
import {
  watchDriBroadcastExpireDrpdwnWorker,
  watchdriverBroadCastExpiredFindOneWorker,
  watchdriverBroadCastExpiredList,
  watchRideBroadcastExpiredDrpdwnWorker,
  watchriderBroadCastExpiredFindOneWorker,
  watchriderBroadCastExpiredListWorker,
} from "./broadcast/expiredBroadcastSaga";
import {
  WatchcomplaintMessageReadWorker,
  WatchfindALLComplaintsWorker,
  WatchfindALLSosMessagesWorker,
  WatchSendSosMessagesWorker,
  WatchsosMessageReadWorker,
  WatchStoredMessagesSosWorker,
  WatchStoredMessagesWorker,
  WatchUploadChatImageWorker,
} from "./chatSectionSaga/chatSectionSaga";
import {
  watchCloseRiderSOSWorker,
  watchCloseSOSWorker,
  watchForwardRiderSOSWorker,
  watchForwardSOSWorker,
  watchmySOSDriverListWorker,
  watchmySOSRiderListWorker,
  watchResolveRiderSOSWorker,
  watchResolveSOSWorker,
} from "./sos/mySOSSage";
import manageZoneRootSaga from "./rootSaga/manageZoneRootSaga";
import manageDriverRootSaga from "./rootSaga/manageDriversRootSaga";
import manageFaresRootSaga from "./rootSaga/manageFaresRootSaga";
import {
  watchriderFaqHelpCovidListWorker,
  watchriderFaqHelpGuideToComrideListWorker,
  watchriderFaqHelpMyTripsListWorker,
  watchriderFaqHelpPaymentListWorker,
  watchriderFaqHelpProfileAccountListWorker,
  watchriderFaqHelpReferalListWorker,
  watchriderFaqHelpSafetyListWorker,
  watchriderFaqHelpTroubleshootListWorker,
} from "./faq/rider/riderFaqHelpSaga";
import {
  watchriderFaqDuringTripLocalistWorker,
  watchriderFaqDuringTripOneWayListWorker,
  watchriderFaqDuringTripRentaListWorker,
  watchriderFaqDuringTripRoundListWorker,
} from "./faq/rider/riderFaqDuringTripSaga";
import {
  watchriderFaqAfterPaymentLocalListWorker,
  watchriderFaqAfterPayOnewayListWorker,
  watchriderFaqAfterPayRentListWorker,
  watchriderFaqAfterPayRoundListWorker,
  watchriderFaqAfterTripLocalListWorker,
  watchriderFaqAfterTripOnewayListWorker,
  watchriderFaqAfterTripRentalListWorker,
  watchriderFaqAfterTripRoundListWorker,
} from "./faq/rider/riderFaqAfterTripSaga";
import {
  watchDriverFaqHelpCancelPolicyListWorker,
  watchDriverFaqHelpComrideServiceListWorker,
  watchDriverFaqHelpCovidListWorker,
  watchDriverFaqHelpGuideToComrideListWorker,
  watchDriverFaqHelpMyAccountListWorker,
  watchDriverFaqHelpPaymentListWorker,
  watchDriverFaqHelpReferalListWorker,
  watchDriverFaqHelpSafetyListWorker,
} from "./faq/driver/driverFaqHelpSaga";
import {
  watchDriverFaqDuringTripLocalListWorker,
  watchDriverFaqDuringTripOnewayListWorker,
  watchDriverFaqDuringTripRentalListWorker,
  watchDriverFaqDuringTripRoundListWorker,
} from "./faq/driver/driverFaqDuringTripSaga";
import {
  watchcreateFaqOrTopicWorker,
  watchviewFaqOrTopicWorker,
  watcheditFaqOrTopicWorker,
  watchdeleteFaqOrTopicWorker,
  watchcreateTopicUnderFaqWorker,
  watcheditTopicUnderFaqWorker,
  watchviewTopicUnderFaqWorker,
  watchdeleteTopicUnderFaqWorker,
  watchTopicUnderFaqRiderListWorker,
  watchTopicUnderFaqDriverListWorker,
  watchactiveFaqOrTopicWorker,
  watchinActiveFaqOrTopicWorker,
} from "./faq/faqSaga";
import {
  WatchNse_R_BookingLocal_AccidentWorker,
  WatchNse_R_BookingLocal_CancelledWorker,
  WatchNse_R_BookingLocal_No_RidesWorker,
  WatchNse_R_BookingLocal_OngoingWorker,
  WatchNse_R_BookingLocal_ReviewWorker,
  WatchNse_R_BookingOneway_AccidentWorker,
  WatchNse_R_BookingOneway_CancelledWorker,
  WatchNse_R_BookingOneway_No_RidesWorker,
  WatchNse_R_BookingOneway_OdometerWorker,
  WatchNse_R_BookingOneway_OngoingWorker,
  WatchNse_R_BookingOneway_ReviewWorker,
  WatchNse_R_BookingOneway_RideScheduledWorker,
  WatchNse_R_BookingRental_AccidentWorker,
  WatchNse_R_BookingRental_CancelledWorker,
  WatchNse_R_BookingRental_No_RidesWorker,
  WatchNse_R_BookingRental_OngoingWorker,
  WatchNse_R_BookingRental_ReviewWorker,
  WatchNse_R_BookingRound_AccidentWorker,
  WatchNse_R_BookingRound_CancelledWorker,
  WatchNse_R_BookingRound_No_RidesWorker,
  WatchNse_R_BookingRound_OdometerWorker,
  WatchNse_R_BookingRound_OngoingWorker,
  WatchNse_R_BookingRound_ReviewWorker,
  WatchNse_R_BookingRound_RideScheduledWorker,
  WatchNse_R_EditWorker,
  WatchNse_R_EmerSOS_DuringTripWorker,
  WatchNse_R_EmerSOS_MessagingWorker,
  WatchNse_R_EmerSOS_NoTripWorker,
  WatchNse_R_FindOneWorker,
  WatchNse_R_GeneralAccountListWorker,
  WatchNse_R_INAPPMESS_ComplaintWorker,
  WatchNse_R_INAPPMESS_PendingWorker,
  WatchNse_R_INAPPMESS_RESCLOSEDWorker,
  WatchNse_R_NewAccountListWorker,
  WatchNse_R_PaymentPendingWorker,
  WatchNse_R_PaymentRiderCBWorker,
  WatchNse_R_PaymentSuccessWorker,
  WatchNse_R_PaymentWalletWorker,
  WatchNse_R_PolicyUpdateListWorker,
  WatchNse_R_SecurityListWorker,
  WatchNse_D_NewAccountListWorker,
  WatchNse_D_NewDriverApplicationListWorker,
  WatchNse_D_ExisDriverApplicationListWorker,
  WatchNse_D_GeneralAccountListWorker,
  WatchNse_D_AccountActivityListWorker,
  WatchNse_D_PolicyUpdateListWorker,
  WatchNse_D_DriverPerformanceListWorker,
  WatchNse_D_SecurityListWorker,
  WatchNse_D_BookingLocal_OngoingListWorker,
  WatchNse_D_BookingLocal_StopAddedListWorker,
  WatchNse_D_BookingLocal_DropOffUpdateListWorker,
  WatchNse_D_BookingLocal_PaymentListWorker,
  WatchNse_D_BookingLocal_CancelledListWorker,
  WatchNse_D_BookingLocal_AccidentListWorker,
  WatchNse_D_BookingLocal_ReviewListWorker,
  WatchNse_D_BookingRental_OngoingListWorker,
  WatchNse_D_BookingRental_DailyLimitReachedListWorker,
  WatchNse_D_BookingRental_DropOffUpdatedWorker,
  WatchNse_D_BookingRental_PaymentListWorker,
  WatchNse_D_BookingRental_CancelledListWorker,
  WatchNse_D_BookingRental_AccidentListWorker,
  WatchNse_D_BookingRental_ReviewListWorker,
  WatchNse_D_BookingOneway_OngoingListWorker,
  WatchNse_D_BookingOneway_OdometerListWorker,
  WatchNse_D_BookingOneway_DropOffUpdatedWorker,
  WatchNse_D_BookingOneway_PaymentListWorker,
  WatchNse_D_BookingOneway_CancelledListWorker,
  WatchNse_D_BookingOneway_AccidentListWorker,
  WatchNse_D_BookingOneway_ReviewListWorker,
  WatchNse_D_BookingOneway_MaxLimitReachedListWorker,
  WatchNse_D_BookingRound_OngoingListWorker,
  WatchNse_D_BookingRound_OdometerListWorker,
  WatchNse_D_BookingRound_DropOffUpdateListWorker,
  WatchNse_D_BookingRound_PaymentListWorker,
  WatchNse_D_BookingRound_CancelledListWorker,
  WatchNse_D_BookingRound_AccidentListWorker,
  WatchNse_D_BookingRound_ReviewListWorker,
  WatchNse_D_BookingRound_MaxLimitReachedListWorker,
  WatchNse_D_BookingRound_ReturnTripListWorker,
  WatchNse_D_PaymentFineWorker,
  WatchNse_D_PaymentReceivedWorker,
  WatchNse_D_PaymentDueWorker,
  WatchNse_D_PaymentDriverCBListWorker,
  WatchNse_D_CashoutListWorker,
  WatchNse_D_EmerSOS_DuringTripWorker,
  WatchNse_D_EmerSOS_NoTripWorker,
  WatchNse_D_EmerSOS_MessagingWorker,
  WatchNse_D_INAPPMESS_DuringTripListWorker,
  WatchNse_D_INAPPMESS_ComplaintWorker,
  WatchNse_D_INAPPMESS_RESCLOSEDWorker,
  WatchNse_D_INAPPMESS_SlotStartTimeListWorker,
  WatchNse_D_INAPPMESS_InprogressListWorker,
  WatchNse_D_INAPPMESS_SlotRemainingTimeListWorker,
  WatchNse_D_INAPPMESS_CompletedSuccessWorker,
  WatchNse_D_FindOneWorker,
  WatchNse_D_EditWorker,
} from "./nse/riderNseSaga";
import {
  watchriderFinanceFindOneWorker,
  watchriderFinanceListWorker,
  watchriderFinanceDropDownListWorker,
} from "./riderFinanceSaga/riderFinanceSaga";
import {
  watchIncentiveMainZoneListWorker,
  watchIncentiveRideTypeListWorker,
} from "./incentives/dropDownSaga";
import {
  watchDrifinCurbalDropdownListWorker,
  watchDriverFinanceCurrentBalanceFindOneWorker,
  watchDriverFinanceCurrentBalanceListWorker,
} from "./driverFinanceSaga/currentBalanceSaga";
import {
  watchDrifinCreatecashDropdownListWorker,
  watchDriverFinanceCreateCashTransactionCreateWorker,
  watchDriverFinanceCreateCashTransactionListWorker,
  watchPremiumPlanCancelActiveWorker,
  watchPremiumPlanCancelScheduleWorker,
  watchPremiumPlanScheduleWorker,
  watchPremiumPlanSwitchWorker,
  watchPremiumPlanWorker,
  watchPremiumSchedulePlanWorker,
} from "./driverFinanceSaga/createCashTransactionSaga";
import {
  watchDrifinCashtransDropdownListWorker,
  watchDriverFinanceCashTransactionHistoryFindOneWorker,
  watchDriverFinanceCashTransactionHistoryListWorker,
} from "./driverFinanceSaga/cashTransactionHistorySaga";
import {
  watchDrifinCashouttransDropdownListWorker,
  watchDriverFinanceCashOutTransactionHistoryFindOneWorker,
  watchDriverFinanceCashOutTransactionHistoryListWorker,
} from "./driverFinanceSaga/cashoutTransactionHistorySaga";
import {
  watchDrifinSucescashDropdownListWorker,
  watchDriverFinanceSuccessfulCashoutFindOneWorker,
  watchDriverFinanceSuccessfulCashoutListWorker,
} from "./driverFinanceSaga/successfulCashoutTransactionSaga";
import {
  watchDrimetDropdownListWorker,
  watchDriverMetricsListWorker,
  watchDriverMetricsViewWorker,
} from "./DriverMetricsSaga/driverMetrics";
import {
  watchDefaultPremiumOneListWorker,
  watchDefaultPremiumOneFindOneWorker,
  watchDefaultPremiumFourViewWorker,
  watchDefaultPremiumFourEditWorker,
  watchManagePremiumFourEditWorker,
  watchManagePremiumListWorker,
  watchManagePremiumRideListWorker,
  watchDefaultPremiumTwoFindOneWorker,
  watchDefaultPremiumThreeFindOneWorker,
  watchDefaultPremiumFiveFindOneWorker,
  watchDefaultPremiumDuedepositWorker,
  watchDefaultPremiumDuedepositEditWorker,
  watchDefaultPremium1235EditWorker,
  watchDefaultPremiumPricingModuleEditApiWorker,
  watchmanagePremiumOneFindOneWorker,
  watchmanagePremiumTwoFindOneWorker,
  watchmanagePremiumThreeFindOneWorker,
  watchmanagePremiumFiveFindOneWorker,
  watchmanagePremiumFourFindOneWorker,
  watchManagePremium1235EditWorker,
  watchManagePremiumDuedepositEditWorker,
  watchManagePremiumPricingModuleEditApiWorker,
  watchManagePremiumDuedepositWorker,
  watchManagePremiumStatusUpdateApiWorker,
  watchManagePremium4SubscriptionWorker,
  watchManagePremium5SubscriptionWorker,
  watchManagePremiumSubscriptionEditWorker,
  watchArchivedPremiumOneFindOneWorker,
  watchArchivedPremiumTwoFindOneWorker,
  watchArchivedPremiumThreeFindOneWorker,
  watchArchivedPremiumFourFindOneWorker,
  watchArchivedPremiumFiveFindOneWorker,
  watchArchivedPremiumDuedepositWorker,
  watchArchivedPremium4SubscriptionWorker,
  watchArchivedPremium5SubscriptionWorker,
  watchArchivedPremiumListWorker,
  watchArchivedPremiumRideListWorker,
  watchAutoReneActiveInactivePremiumWorker,
  watchCancelAutoRenewalPremiumWorker,
  watchCancelActiveAutoRenewalPremiumWorker,
  watchCancelActiveScheduledPremiumWorker,
  watchManagePremium6DuesEditApiWorker,
  watchPremiumUploadImageWorker,
  watchmanagePremiumSixFindOneWorker,
  watchDefaultPremiumSixFindOneWorker,
  watchManagePremium6SubscriptionWorker,
  watchManagePremium6SubscriptionEditWorker,
  watchManagePremium6StatusUpdateApiWorker,
} from "./premiumSaga/defaultPremiumSaga";
import {
  premiumCancelledRefundListWorker,
  premiumSucessfulRefundListWorker,
  watchPremiumCancelledRefundListWorker,
  watchPremiumCancelledRefundViewWorker,
  watchPremiumPendinfRefundUpdateWorker,
  watchPremiumPendinfRefundViewWorker,
  watchPremiumPendingRefundListWorker,
  watchPremiumRefundCancelWorker,
  watchPremiumSucessfulRefundListWorker,
  watchPremiumSucessfulRefundViewWorker,
} from "./premiumRefundSaga";
import {
  watchdashboardDetailsWorker,
  watchdashboardGraphDetailsWorker,
  watchdashboardMoreGraphDetailsWorker,
} from "./dashboard/dashboardSaga";
import { watchTrackingListWorkerWorker } from "./TRACKING/tracking-saga";

export default function* rootSaga() {
  yield all([
    watchLoginWorker(),
    watchLogoutWorker(),
    watchresetAdminPasswordWorker(),
    watchResetLogoutAdminPasswordWorker(),
    watchdashboardGraphDetailsWorker(),
    watchdashboardMoreGraphDetailsWorker(),
    watchdashboardDetailsWorker(),
    /********Manage Admins ****************/
    watchblockedDropdownListWorker(),
    watchdeletedDropdownListWorker(),
    watchDropdownListWorker(),
    watchAddAdminWorker(),

    watchAdminListWorker(),
    watchAdminFindOneWorker(),
    watchEditAdminWorker(),
    watchBlockAdminListWorker(),
    watchBlockedEditAdminWorker(),
    watchBlockAdminWorker(),
    watchDeleteAdminWorker(),
    watchUnblockAdminWorker(),
    watchDeletedAdminListWorker(),

    /********Manage Riders *********/
    watchRiderDropDownListWorker(),
    watchBlockedRiderDropDownListWorker(),
    watchdelRiderDropDownListWorker(),
    watchperDelRiderDropDownListWorker(),
    watchRiderListWorker(),
    watchRiderViewWorker(),
    watchRiderHistoryViewWorker(),
    watchBlockedRiderHistoryViewWorker(),
    watchDeletedRiderHistoryViewWorker(),
    watchresetRiderRatingWorker(),
    watchresetRiderPictureWorker(),
    watchactivateRiderWorker(),
    watchblockRiderWorker(),
    watchdeleteRiderWorker(),
    watchblockedRiderListWorker(),
    watchblockedRiderViewWorker(),
    watchUnblockRiderViewWorker(),
    watchDeletedRiderListWorker(),
    watchDeletedRiderViewWorker(),
    watchRestoreRiderViewWorker(),
    watchPermanentlyDeleteRiderWorker(),
    watchpermanentDelRiderListWorker(),
    watchpermanentDelRiderViewWorker(),

    /************Manage Drivers **********/

    manageDriverRootSaga(),

    /****************Fares *****************/
    manageFaresRootSaga(),

    // refund
    watchpendingRefundListWorker(),
    watchpendinfRefundViewWorker(),
    watchpendinfRefundUpdateWorker(),
    watchsucessfulRefundListWorker(),
    watchsucessfulRefundViewWorker(),
    watchcancelledRefundListWorker(),
    watchcancelledRefundViewWorker(),
    watchsucessRefundDropdownListWorker(),
    watchCancelRefundDropdownListWorker(),
    watchpendRefundDropdownListWorker(),

    // rideType

    watchaddRideTypeWorker(),
    watchrideTypeZoneListWorker(),
    watchrideTypeListWorker(),
    watchrideTypeViewWorker(),
    watchrideTypeUpdateWorker(),
    watchvehicleTypeListWorker(),
    watchaddVehicleTypeWorker(),
    watchrideTypeDropdownWorker(),
    watchvehicleTypeViewWorker(),
    watchvehicleTypeUpdateWorker(),
    watchuploadImageRideTypeWorker(),
    watchrideTypeDropDownListWorker(),
    watchvehicleTypeDropDownListWorker(),
    watchdeleteRideTypeWorker(),

    /*************Manage booking Request ***********/

    watchongoingRequestListWorker(),
    watchongoingRequestIndividualWorker(),
    watchunSuccessfulRequestListWorker(),
    watchunSuccessfulRequestIndividualWorker(),
    watchOngoingDropDownListWorker(),
    watchUnsuccessfulDropDownListWorker(),

    /*************Manage booking ***********/

    watchongoingBookingListWorker(),
    watchongoingBookingIndividualWorker(),
    watchongoingDriverReqCancelWorker(),
    watchongoingRiderReqCancelWorker(),
    watchongoingAccidentReportWorker(),
    watchongoingEndTripWorker(),
    watchongoingUpdatePaymentMethodWorker(),
    watchongoingUpdateBillingDetailsWorker(),
    watchongoingUpdateInitialOdometerWorker(),
    watchongoingUpdateFinalOdometerWorker(),
    watchOngoingBookingsDropDownListWorker(),
    watchcompletedBookingListWorker(),
    watchcompletedBookingIndividualWorker(),
    watchcompletedUpdatePaymentMethodWorker(),
    watchcompletedUpdateBillingDetailsWorker(),
    watchcompletedUpdateInitialOdometerWorker(),
    watchcompletedUpdateFinalOdometerWorker(),
    watchcompletedBookingCreateRefundWorker(),
    watchcompletedBookingCancelRefundWorker(),
    watchcompletedBookingCancelDriverFineWorker(),
    watchCompletedBookingsDropDownListWorker(),
    watchcancelledBookingListWorker(),
    watchcancelledBookingIndividualWorker(),
    watchcancelledBookingUpdateBillingWorker(),
    watchcancelledUpdateInitialOdometerWorker(),
    watchcancelledUpdateFinalOdometerWorker(),
    watchcancelledUpdatePaymentMethodWorker(),
    watchcancelledBookingCreateRefundWorker(),
    watchcancelledBookingCancelRefundWorker(),
    watchcancelledBookingCancelDriverFineWorker(),
    watchCancelledBookingsDropDownListWorker(),
    watchaccidentBookingListWorker(),
    watchaccidentUpdatePaymentMethodWorker(),
    watchaccidentUpdateInitialOdometerWorker(),
    watchaccidentUpdateFinalOdometerWorker(),
    watchaccidentBookingCreateRefundWorker(),
    watchaccidentBookingCancelRefundWorker(),
    watchaccidentBookingCancelDriverFineWorker(),
    watchaccidentBookingIndividualWorker(),
    watchaccidentBookingUpdateBillingsWorker(),
    watchAccidentBookingsDropDownListWorker(),
    watchadjustedBookingListWorker(),
    watchadjustedBookingIndividualWorker(),
    watchadjustedBookingsDropDownListWorker(),

    /******** trip invoice ********/
    watchtripInvoiceListWorker(),
    watchtripInvoiceWorker(),
    watchtripInvoiceDropDownListWorker(),

    /*************Manage zones ***********/
    manageZoneRootSaga(),

    /********Driver coupons *************/
    watchcreateDriverCouponWorker(),
    watchcreateDriverCouponBroadcastWorker(),
    watchreviewReqDriverCouponListWorker(),
    watchactiveDriverCouponListWorker(),
    watchactiveDriverCouponWorker(),
    watchactiveDriverCouponEditWorker(),
    watchactiveDriverCouponBroadcastEditWorker(),
    watchrejectedDriverCouponListWorker(),
    watchrejectedDriverCouponWorker(),
    watchdeletedDriverCouponListWorker(),
    watchdeletedDriverCouponWorker(),
    watchdeleteDriverCouponWorker(),
    watchexpiredDriverCouponListWorker(),
    watchexpiredDriverCouponWorker(),
    watchusageHistoryDriverCouponListWorker(),
    watchusageHistoryDriverCouponWorker(),
    watchreviewReqDriverCouponWorker(),
    watchreviewReqDriverCouponEditWorker(),
    watchapproveDriverCouponWorker(),
    watchrejectDriverCouponWorker(),
    watchdropDownListDriverCouponWorker(),
    watchdropDownListDriverCouponActiveWorker(),
    watchdropDownListDriverCouponRejectedWorker(),
    watchdropDownListDriverCouponDeletedWorker(),
    watchdropDownListDriverCouponExpiredWorker(),
    watchdropDownListDriverCouponUsageWorker(),
    // rider coupon
    watchcreateGeneralWorker(),
    watchcreateNewAccountWorker(),
    watchcreateNewAccountLifeSpanWorker(),
    watchcreatePaymentMethodWorker(),
    watchcreateBookingDestinationWorker(),
    watchcreatePickupDropoffWorker(),
    watchcreateRentalPackageWorker(),
    watchcreateBookingDistanceWorker(),
    watchcreateOutstationPackageWorker(),
    watchdropDownListRiderCouponWorker(),
    watchdropDownListRiderCouponActiveWorker(),
    watchdropDownListRiderCouponRejectedWorker(),
    watchdropDownListRiderCouponDeletedWorker(),
    watchdropDownListRiderCouponExpiredWorker(),
    watchdropDownListRiderCouponUsageWorker(),
    watchcouponRideTypeListWorker(),

    // zonelist
    watchcouponMainZoneListApiWorker(),
    watchcouponLocalZoneListWorkerWorker(),
    watchcouponSpecialZoneListWorkerWorker(),
    watchcouponOustationZoneListWorkerWorker(),

    // send review
    watchsendReviewWorker(),
    watchactiveCouponSendReviewWorker(),

    // view coupon all
    watchpendingCouponAllViewWorker(),
    watchactiveCouponAllViewWorker(),
    watchrejectedCouponAllViewWorker(),
    watchdeletedCouponAllViewWorker(),
    watchexpiredCouponAllViewWorker(),
    watchcouponUsageHistoryAllViewWorker(),

    // find one coupon
    watchpendingCouponFindOneWorker(),
    watchactiveCouponFindOneWorker(),
    watchrejectedCouponFindOneWorker(),
    watchdeletedCouponFindOneWorker(),
    watchexpiredCouponFindOneWorker(),
    watchcouponUsageHistoryFindOneWorker(),

    // edit coupon
    watchgeneralCouponEditWorker(),
    watchnewAccountCouponEditWorker(),
    watchnewAccountLifeSpanCouponEditWorker(),
    watchpaymentMethodCouponEditWorker(),
    watchbookingDestinationCouponEditWorker(),
    watchpickUpDropOffCouponEditWorker(),
    watchrentalPackageCouponEditWorker(),
    watchbookingDistanceCouponEditWorker(),
    watchoutStationPackageCouponEditWorker(),
    watchactiveCouponEditWorker(),

    // approve coupon
    watchapproveCouponWorker(),
    // reject coupon
    watchrejectCouponWorker(),
    // delete coupon
    watchdeleteCouponWorker(),
    WatchclearRiderCouponWorker(),
    WatchclearDriverCouponWorker(),

    // imgae upload coupon
    watchuploadImageCouponWorker(),

    // referral
    watchcreateReferralWorker(),

    // send review referral
    watchsendReviewReferralWorker(),

    // find all referral
    watchreviewRequiredReferralAllViewWorker(),
    watchactiveReferralAllViewWorker(),
    watchrejectedReferralAllViewWorker(),
    watchdeletedReferralAllViewWorker(),
    watchexpiredReferralAllViewWorker(),
    WatchriderRefSenderFindAllusageHistoryWorker(),
    WatchriderRefReceiverFindAllusageHisWorker(),

    // find one referral
    watchreviewRequiredReferralFindOneWorker(),
    watchactiveReferralFindOneWorker(),
    watchrejectedReferralFindOneWorker(),
    watchdeletedReferralFindOneWorker(),
    watchexpiredReferralFindOneWorker(),
    WatchriderRefSenderFindOneUsageHistoryWorker(),
    WatchriderRefReceiverFindOneUsageHisWorker(),

    // approve referral
    watchapproveReferralWorker(),

    // reject referral
    watchrejectReferralWorker(),

    // delete referral
    watchdeleteReferralWorker(),

    // edit referral
    watchreviewReqReferralEditWorker(),
    watchreviewReqReferralBroadcastEditWorker(),
    WatchactiveReferralEditWorker(),
    WatchactiveReferralBroadcastEditWorker(),
    WatchclearRiderReferralWorker(),
    WatchclearDriverReferralWorker(),

    watchdropDownListRiderReferralWorker(),
    watchdropDownListRiderReferralActiveWorker(),
    watchdropDownListRiderReferralRejectedWorker(),
    watchdropDownListRiderReferralDeletedWorker(),
    watchdropDownListRiderReferralExpiredWorker(),
    watchdropDownListRiderReferralUsageWorker(),
    /********Driver Referral*******/
    watchReviewReqDriverRefListWorker(),
    watchactiveDriverRefListWorker(),
    watchapproveDriverRefWorker(),
    watchactiveDriverRefFindOneWorker(),
    WatchactiveDriverRefEditWorker(),
    WatchactiveDriverRefBroadcastEditWorker(),
    watchrejectedDriverRefListWorker(),
    watchdelDriverRefListWorker(),
    watchexpiredDriverRefIdListWorker(),
    createDriverToDriverReferralWatcher(),
    createDriverToRiderReferralWatcher(),
    watchreviewReqDriverRefWorker(),
    watchreviewDriverRefD_To_DEditWorker(),
    watchreviewReqDriverRefBroadcastEditWorker(),
    watchsendReviewDriverReferralWorker(),
    watchreviewDriverRefD_To_REditWorker(),
    WatchDriverRefSenderusageHistoryListWorker(),
    WatchDriverRefSenderUsageHistoryWorker(),
    WatchDriverRefReceiverUsageHistoryListWorker(),
    WatchDriverRefReceiverUsageHistoryWorker(),
    watchdeleteDriverRefWorker(),
    watchdelDriverRefListWorker(),
    watchdeletedDriverRefWorker(),
    watchrejectDriverRefWorker(),
    watchrejectedDriverRefListWorker(),
    watchrejectedDriverRefWorker(),
    watchexpiredDriverRefIdWorker(),

    watchdropDownListDriverReferralWorker(),
    watchdropDownListDriverReferralActiveWorker(),
    watchdropDownListDriverReferralRejectedWorker(),
    watchdropDownListDriverReferralDeletedWorker(),
    watchdropDownListDriverReferralExpiredWorker(),
    watchdropDownListDriverReferralUsageWorker(),
    watchreferralRideTypeListWorker(),

    /***********************Complaints ************/
    watchRiderPendComplaintsListWorker(),
    watchDriverPendComplaintsListWorker(),
    watchRiderInprogressComplaintsListWorker(),
    watchDriverInprogressComplaintsListWorker(),
    watchRiderResolvedClosedComplaintsListWorker(),
    watchDriverResolvedClosedComplaintsListWorker(),
    watchRiderPendComplaintWorker(),
    watchRiderInprogressComplaintWorker(),
    watchDriverPendComplaintWorker(),
    watchDriverInprogressComplaintWorker(),
    watchDriverComplaintInitiateWorker(),
    watchRiderComplaintInitiateWorker(),
    watchDriverComplaintAssignWorker(),
    watchRiderComplaintAssignWorker(),
    watchAssignToAdminListWorker(),
    watchdriverInProgComplaintReAssignWorker(),
    watchriderInProgComplaintReAssignWorker(),
    watchbookingIDListWorker(),
    watchRiderResClosedComplaintWorker(),
    watchDriverResClosedComplaintWorker(),
    watchLocalResponderListWorker(),
    watchgenerateComplaintRiderWorker(),
    watchgenerateComplaintDriverWorker(),
    watchcallComplaintDescriptionWorker(),
    watchriderComplPendingDropDownWorker(),
    watchdriverComplPendingDropDownWorker(),
    watchriderComplInprogressDropDownWorker(),
    watchdriverComplInprogressDropDownWorker(),
    watchriderComplReslovedDropDownWorker(),
    watchdriverComplReslovedDropDownWorker(),

    watchRiderPendSOSListWorker(),
    watchDriverPendSOSListWorker(),
    watchRiderPendSOSWorker(),
    watchDriverPendSOSWorker(),
    watchDriverSOSInitiateWorker(),
    watchRiderSOSInitiateWorker(),
    watchDriverSOSAssignWorker(),
    watchRiderSOSAssignWorker(),

    watchRiderInprogressSOSListWorker(),
    watchDriverInprogressSOSListWorker(),
    watchRiderInprogressSOSWorker(),
    watchDriverInprogressSOSWorker(),
    watchdriverInProgSOSReAssignWorker(),
    watchriderInProgSOSReAssignWorker(),
    watchriderIDListApiWorker(),
    watchdriverIDListApiWorker(),

    watchRiderResolvedClosedSOSListWorker(),
    watchDriverResolvedClosedSOSListWorker(),
    watchRiderResClosedSOSWorker(),
    watchDriverResClosedSOSWorker(),
    watchgenerateSosCallRiderWorker(),
    watchgenerateSosCallDriverWorker(),
    watchassignSosToAdminListWorker(),
    watchriderSOSPendingDropDownWorker(),
    watchdriverSOSPendingDropDownWorker(),
    watchriderSOSInprogressDropDownWorker(),
    watchdriverSOSInprogressDropDownWorker(),
    watchmySOSDriverListWorker(),
    watchmySOSRiderListWorker(),
    watchCloseSOSWorker(),
    watchResolveSOSWorker(),
    watchForwardSOSWorker(),
    watchCloseRiderSOSWorker(),
    watchResolveRiderSOSWorker(),
    watchForwardRiderSOSWorker(),

    watchLocalResponderListWorker(),
    watchLocalResponderWorker(),
    watchaddLocalResponderWorker(),
    watchLocalResponderUpdateWorker(),
    watchLocalResponderDeleteWorker(),
    watchLocalResponderConatctListWorker(),

    watchmyComplaintsListWorker(),
    watchmyComplaintsRiderListWorker(),
    watchresolveDriverComplaintWorker(),
    watchCloseDriverCompliantWorker(),
    watchforwardDriverComplaintWorker(),

    watchresolveRiderComplaintWorker(),
    watchCloseRiderCompliantWorker(),
    watchforwardRiderComplaintWorker(),

    // incentive
    watchcreateDriverIncentiveWorker(),
    watchdriverIncentivePendingListWorker(),
    watchdriverIncentivePendingWorker(),
    watchdriverIncentivePendingEditWorker(),
    watchdriverIncentiveActiveListWorker(),
    watchdriverIncentiveActiveWorker(),
    watchdriverIncentiveActiveCampaignEditWorker(),
    watchdriverIncentiveActiveEditWorker(),
    watchApproveDriverIncentiveWorker(),

    watchdriverIncentiveRejectedListWorker(),
    watchdriverIncentiveRejectedWorker(),
    watchrejcectDriverIncentiveWorker(),

    watchdriverIncentiveDeletedListWorker(),
    watchdriverIncentiveDeletedWorker(),
    watchdeleteDriverIncentiveWorker(),

    watchdriverIncentiveExpiredListWorker(),
    watchdriverIncentiveExpiredWorker(),
    watchIncentiveMainZoneListWorker(),
    watchIncentiveRideTypeListWorker(),

    watchDriIncentiveExpireDrpdwnWorker(),
    watchDriIncentiveRejectDrpdwnWorker(),
    watchDriIncentiveDeleteDrpdwnWorker(),
    watchDriIncentiveRevreqDrpdwnWorker(),
    watchDriIncentiveActiveDrpdwnWorker(),
    watchDriIncentiveUdghisDrpdwnWorker(),

    watchdriverIncentiveUseageHisListWorker(),
    watchdriverIncentiveUseageHisWorker(),
    watchriderBroadCastPendingListWorker(),
    watchriderBroadCastActiveListWorker(),
    watchriderBroadCastRejectListWorker(),
    watchriderBroadCastDeleteListWorker(),
    watchriderBroadCastExpiredListWorker(),
    watchriderBroadCastCreateWorker(),
    watchreviewReqRiderBroadCastWorker(),
    watchreviewReqRiderBroadCastEditWorker(),
    watchriderBroadCastApproveWorker(),
    watchriderBroadCastRejectWorker(),
    watchriderBroadCastDeleteWorker(),
    watchriderBroadCastDeleteFindOneWorker(),
    watchdriverBroadCastActiveListWorker(),
    watchActiveRiderBroadCastEditWorker(),
    watchactiveRiderBroadCastFindOneWorker(),
    watchdriverBroadCastDeleteListWorker(),
    watchdriverBroadCastExpiredList(),
    watchriderBroadCastExpiredFindOneWorker(),
    watchdriverBroadCastRejectListWorker(),
    watchriderBroadCastRejectFindOneWorker(),
    watchdriverBroadCastPendingListWorker(),
    watchreviewReqDriverBroadCastWorker(),
    watchactivedriverBroadCastFindOneWorker(),
    watchdriverBroadCastDeleteFindOneWorker(),
    watchdriverBroadCastExpiredFindOneWorker(),
    watchdriverBroadCastRejectFindOneWorker(),
    watchdriverBroadCastCreateWorker(),
    watchdriverBroadCastApproveWorker(),
    watchdriverBroadCastRejectWorker(),
    watchreviewReqDriverBroadCastEditWorker(),
    watchrideTypeBroadcastDropdownWorker(),
    watchActiveDriverBroadCastEditWorker(),
    watchdriverBroadCastDeleteWorker(),

    watchRideBroadcastRevreqDrpdwnWorker(),
    watchRideBroadcastActiveDrpdwnWorker(),
    watchRideBroadcastRejectDrpdwnWorker(),
    watchRideBroadcastDeleteDrpdwnWorker(),
    watchRideBroadcastExpiredDrpdwnWorker(),

    watchDriBroadcastRevreqDrpdwnWorker(),
    watchDriBroadcastActiveDrpdwnWorker(),
    watchDriBroadcastRejectDrpdwnWorker(),
    watchDriBroadcastDeleteDrpdwnWorker(),
    watchDriBroadcastExpireDrpdwnWorker(),

    // chat
    WatchStoredMessagesWorker(),
    WatchStoredMessagesSosWorker(),
    WatchfindALLComplaintsWorker(),
    WatchfindALLSosMessagesWorker(),
    WatchcomplaintMessageReadWorker(),
    WatchsosMessageReadWorker(),
    WatchUploadChatImageWorker(),
    WatchSendSosMessagesWorker(),
    // Faq
    watchriderFaqHelpCovidListWorker(),
    watchriderFaqHelpProfileAccountListWorker(),
    watchriderFaqHelpMyTripsListWorker(),
    watchriderFaqHelpPaymentListWorker(),
    watchriderFaqHelpSafetyListWorker(),
    watchriderFaqHelpTroubleshootListWorker(),
    watchriderFaqHelpGuideToComrideListWorker(),
    watchriderFaqHelpReferalListWorker(),
    watchriderFaqDuringTripLocalistWorker(),
    watchriderFaqDuringTripRentaListWorker(),
    watchriderFaqDuringTripOneWayListWorker(),
    watchriderFaqDuringTripRoundListWorker(),
    watchriderFaqAfterTripLocalListWorker(),
    watchriderFaqAfterTripRentalListWorker(),
    watchriderFaqAfterTripOnewayListWorker(),
    watchriderFaqAfterTripRoundListWorker(),
    watchriderFaqAfterPaymentLocalListWorker(),
    watchriderFaqAfterPayRentListWorker(),
    watchriderFaqAfterPayOnewayListWorker(),
    watchriderFaqAfterPayRoundListWorker(),
    watchDriverFaqHelpCovidListWorker(),
    watchDriverFaqHelpMyAccountListWorker(),
    watchDriverFaqHelpCancelPolicyListWorker(),
    watchDriverFaqHelpPaymentListWorker(),
    watchDriverFaqHelpSafetyListWorker(),
    watchDriverFaqHelpComrideServiceListWorker(),
    watchDriverFaqHelpGuideToComrideListWorker(),
    watchDriverFaqHelpReferalListWorker(),
    watchDriverFaqDuringTripLocalListWorker(),
    watchDriverFaqDuringTripRentalListWorker(),
    watchDriverFaqDuringTripOnewayListWorker(),
    watchDriverFaqDuringTripRoundListWorker(),
    watchcreateFaqOrTopicWorker(),
    watchviewFaqOrTopicWorker(),
    watcheditFaqOrTopicWorker(),
    watchdeleteFaqOrTopicWorker(),
    watchcreateTopicUnderFaqWorker(),
    watcheditTopicUnderFaqWorker(),
    watchviewTopicUnderFaqWorker(),
    watchdeleteTopicUnderFaqWorker(),
    watchTopicUnderFaqRiderListWorker(),
    watchTopicUnderFaqDriverListWorker(),
    watchactiveFaqOrTopicWorker(),
    watchinActiveFaqOrTopicWorker(),

    // nse
    WatchNse_R_NewAccountListWorker(),
    WatchNse_R_GeneralAccountListWorker(),
    WatchNse_R_PolicyUpdateListWorker(),
    WatchNse_R_SecurityListWorker(),
    WatchNse_R_BookingLocal_No_RidesWorker(),
    WatchNse_R_BookingLocal_OngoingWorker(),
    WatchNse_R_BookingLocal_CancelledWorker(),
    WatchNse_R_BookingLocal_AccidentWorker(),
    WatchNse_R_BookingLocal_ReviewWorker(),
    WatchNse_R_BookingRental_No_RidesWorker(),
    WatchNse_R_BookingRental_OngoingWorker(),
    WatchNse_R_BookingRental_CancelledWorker(),
    WatchNse_R_BookingRental_AccidentWorker(),
    WatchNse_R_BookingRental_ReviewWorker(),
    WatchNse_R_BookingOneway_No_RidesWorker(),
    WatchNse_R_BookingOneway_OngoingWorker(),
    WatchNse_R_BookingOneway_CancelledWorker(),
    WatchNse_R_BookingOneway_AccidentWorker(),
    WatchNse_R_BookingOneway_ReviewWorker(),
    WatchNse_R_BookingOneway_RideScheduledWorker(),
    WatchNse_R_BookingOneway_OdometerWorker(),
    WatchNse_R_BookingRound_No_RidesWorker(),
    WatchNse_R_BookingRound_OngoingWorker(),
    WatchNse_R_BookingRound_CancelledWorker(),
    WatchNse_R_BookingRound_AccidentWorker(),
    WatchNse_R_BookingRound_ReviewWorker(),
    WatchNse_R_BookingRound_RideScheduledWorker(),
    WatchNse_R_BookingRound_OdometerWorker(),
    WatchNse_R_PaymentPendingWorker(),
    WatchNse_R_PaymentSuccessWorker(),
    WatchNse_R_PaymentRiderCBWorker(),
    WatchNse_R_PaymentWalletWorker(),
    WatchNse_R_EmerSOS_DuringTripWorker(),
    WatchNse_R_EmerSOS_NoTripWorker(),
    WatchNse_R_EmerSOS_MessagingWorker(),
    WatchNse_R_INAPPMESS_PendingWorker(),
    WatchNse_R_INAPPMESS_ComplaintWorker(),
    WatchNse_R_INAPPMESS_RESCLOSEDWorker(),
    WatchNse_R_FindOneWorker(),
    WatchNse_R_EditWorker(),
    WatchNse_D_NewAccountListWorker(),
    WatchNse_D_NewDriverApplicationListWorker(),
    WatchNse_D_ExisDriverApplicationListWorker(),
    WatchNse_D_GeneralAccountListWorker(),
    WatchNse_D_AccountActivityListWorker(),
    WatchNse_D_PolicyUpdateListWorker(),
    WatchNse_D_DriverPerformanceListWorker(),
    WatchNse_D_SecurityListWorker(),
    WatchNse_D_BookingLocal_OngoingListWorker(),
    WatchNse_D_BookingLocal_StopAddedListWorker(),
    WatchNse_D_BookingLocal_DropOffUpdateListWorker(),
    WatchNse_D_BookingLocal_PaymentListWorker(),
    WatchNse_D_BookingLocal_CancelledListWorker(),
    WatchNse_D_BookingLocal_AccidentListWorker(),
    WatchNse_D_BookingLocal_ReviewListWorker(),
    WatchNse_D_BookingRental_OngoingListWorker(),
    WatchNse_D_BookingRental_DailyLimitReachedListWorker(),
    WatchNse_D_BookingRental_DropOffUpdatedWorker(),
    WatchNse_D_BookingRental_PaymentListWorker(),
    WatchNse_D_BookingRental_CancelledListWorker(),
    WatchNse_D_BookingRental_AccidentListWorker(),
    WatchNse_D_BookingRental_ReviewListWorker(),
    WatchNse_D_BookingOneway_OngoingListWorker(),
    WatchNse_D_BookingOneway_OdometerListWorker(),
    WatchNse_D_BookingOneway_DropOffUpdatedWorker(),
    WatchNse_D_BookingOneway_PaymentListWorker(),
    WatchNse_D_BookingOneway_CancelledListWorker(),
    WatchNse_D_BookingOneway_AccidentListWorker(),
    WatchNse_D_BookingOneway_ReviewListWorker(),
    WatchNse_D_BookingOneway_MaxLimitReachedListWorker(),
    WatchNse_D_BookingRound_OngoingListWorker(),
    WatchNse_D_BookingRound_OdometerListWorker(),
    WatchNse_D_BookingRound_DropOffUpdateListWorker(),
    WatchNse_D_BookingRound_PaymentListWorker(),
    WatchNse_D_BookingRound_CancelledListWorker(),
    WatchNse_D_BookingRound_AccidentListWorker(),
    WatchNse_D_BookingRound_ReviewListWorker(),
    WatchNse_D_BookingRound_MaxLimitReachedListWorker(),
    WatchNse_D_BookingRound_ReturnTripListWorker(),
    WatchNse_D_PaymentFineWorker(),
    WatchNse_D_PaymentReceivedWorker(),
    WatchNse_D_PaymentDueWorker(),
    WatchNse_D_PaymentDriverCBListWorker(),
    WatchNse_D_CashoutListWorker(),
    WatchNse_D_EmerSOS_DuringTripWorker(),
    WatchNse_D_EmerSOS_NoTripWorker(),
    WatchNse_D_EmerSOS_MessagingWorker(),
    WatchNse_D_INAPPMESS_DuringTripListWorker(),
    WatchNse_D_INAPPMESS_ComplaintWorker(),
    WatchNse_D_INAPPMESS_RESCLOSEDWorker(),
    WatchNse_D_INAPPMESS_SlotStartTimeListWorker(),
    WatchNse_D_INAPPMESS_InprogressListWorker(),
    WatchNse_D_INAPPMESS_SlotRemainingTimeListWorker(),
    WatchNse_D_INAPPMESS_CompletedSuccessWorker(),
    WatchNse_D_FindOneWorker(),
    WatchNse_D_EditWorker(),

    /********Rider Finance*******/
    watchriderFinanceListWorker(),
    watchriderFinanceFindOneWorker(),
    watchriderFinanceDropDownListWorker(),
    watchTrackingListWorkerWorker(),

    /********Driver Finance*******/
    watchDriverFinanceCurrentBalanceListWorker(),
    watchDriverFinanceCurrentBalanceFindOneWorker(),
    watchDriverFinanceCreateCashTransactionListWorker(),
    watchDriverFinanceCreateCashTransactionCreateWorker(),
    watchDriverFinanceCashTransactionHistoryListWorker(),
    watchDriverFinanceCashTransactionHistoryFindOneWorker(),
    watchDriverFinanceCashOutTransactionHistoryListWorker(),
    watchDriverFinanceCashOutTransactionHistoryFindOneWorker(),
    watchDriverFinanceSuccessfulCashoutListWorker(),
    watchDriverFinanceSuccessfulCashoutFindOneWorker(),
    watchDrifinCurbalDropdownListWorker(),
    watchDrifinCreatecashDropdownListWorker(),
    watchPremiumPlanWorker(),
    watchPremiumSchedulePlanWorker(),
    watchPremiumPlanSwitchWorker(),
    watchPremiumPlanScheduleWorker(),
    watchPremiumPlanCancelScheduleWorker(),
    watchPremiumPlanCancelActiveWorker(),
    watchDrifinSucescashDropdownListWorker(),
    watchDrifinCashtransDropdownListWorker(),
    watchDrifinCashouttransDropdownListWorker(),

    /********** Driver Metrics **************/
    watchDriverMetricsListWorker(),
    watchDriverMetricsViewWorker(),
    watchDrimetDropdownListWorker(),

    /********** DefaultPremium**************/
    watchDefaultPremiumOneListWorker(),
    watchDefaultPremiumOneFindOneWorker(),
    watchDefaultPremiumTwoFindOneWorker(),
    watchDefaultPremiumThreeFindOneWorker(),
    watchDefaultPremiumFiveFindOneWorker(),
    watchDefaultPremiumSixFindOneWorker(),
    watchDefaultPremium1235EditWorker(),
    watchDefaultPremiumFourViewWorker(),
    watchDefaultPremiumFourEditWorker(),
    watchManagePremiumFourEditWorker(),
    watchManagePremiumListWorker(),
    watchManagePremiumRideListWorker(),
    watchDefaultPremiumDuedepositWorker(),
    watchManagePremiumDuedepositWorker(),
    watchDefaultPremiumDuedepositEditWorker(),
    watchDefaultPremiumPricingModuleEditApiWorker(),
    watchmanagePremiumOneFindOneWorker(),
    watchmanagePremiumTwoFindOneWorker(),
    watchmanagePremiumThreeFindOneWorker(),
    watchmanagePremiumFourFindOneWorker(),
    watchmanagePremiumFiveFindOneWorker(),
    watchmanagePremiumSixFindOneWorker(),
    watchManagePremium1235EditWorker(),
    watchManagePremiumDuedepositEditWorker(),
    watchManagePremiumPricingModuleEditApiWorker(),
    watchManagePremiumStatusUpdateApiWorker(),
    watchManagePremium6StatusUpdateApiWorker(),
    watchManagePremium6DuesEditApiWorker(),
    watchManagePremium4SubscriptionWorker(),
    watchManagePremium5SubscriptionWorker(),
    watchManagePremium6SubscriptionWorker(),
    watchPremiumUploadImageWorker(),
    watchManagePremiumSubscriptionEditWorker(),
    watchManagePremium6SubscriptionEditWorker(),
    watchArchivedPremiumOneFindOneWorker(),
    watchArchivedPremiumTwoFindOneWorker(),
    watchArchivedPremiumThreeFindOneWorker(),
    watchArchivedPremiumFourFindOneWorker(),
    watchArchivedPremiumFiveFindOneWorker(),
    watchArchivedPremiumDuedepositWorker(),
    watchArchivedPremium4SubscriptionWorker(),
    watchArchivedPremium5SubscriptionWorker(),
    watchArchivedPremiumListWorker(),
    watchArchivedPremiumRideListWorker(),
    watchAutoReneActiveInactivePremiumWorker(),
    watchCancelAutoRenewalPremiumWorker(),
    watchCancelActiveAutoRenewalPremiumWorker(),
    watchCancelActiveScheduledPremiumWorker(),

    watchPremiumPendingRefundListWorker(),
    watchPremiumCancelledRefundListWorker(),
    watchPremiumSucessfulRefundListWorker(),
    watchPremiumPendinfRefundViewWorker(),
    watchPremiumCancelledRefundViewWorker(),
    watchPremiumSucessfulRefundViewWorker(),
    watchPremiumPendinfRefundUpdateWorker(),
    watchPremiumRefundCancelWorker(),
  ]);
}
