export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGIN_LOADING = "ADMIN_LOGIN_LOADING";

export const PENDING_APPLICANT_DATA_LOADING = "PENDING_APPLICANT_DATA_LOADING";
export const PENDING_APPLICANT_DATA_LOADED = "PENDING_APPLICANT_DATA_LOADED";
export const PENDING_APPLICANT_DATA_FAILED = "PENDING_APPLICANT_DATA_FAILED";

export const BANNED_APPLICANT_DATA_LOADING = "BANNED_APPLICANT_DATA_LOADING";
export const BANNED_APPLICANT_DATA_LOADED = "BANNED_APPLICANT_DATA_LOADED";
export const BANNED_APPLICANT_DATA_FAILED = "BANNED_APPLICANT_DATA_FAILED";

export const REJECT_APPLICANT_DATA_LOADING = "REJECT_APPLICANT_DATA_LOADING";
export const REJECT_APPLICANT_DATA_LOADED = "REJECT_APPLICANT_DATA_LOADED";
export const REJECT_APPLICANT_DATA_FAILED = "REJECT_APPLICANT_DATA_FAILED";

export const Expired_APPLICANT_DATA_LOADING = "Expired_APPLICANT_DATA_LOADING";
export const Expired_APPLICANT_DATA_LOADED = "Expired_APPLICANT_DATA_LOADED";
export const Expired_APPLICANT_DATA_FAILED = "Expired_APPLICANT_DATA_FAILED";

export const BLOCKED_APPLICANT_DATA_LOADING = "BLOCKED_APPLICANT_DATA_LOADING";
export const BLOCKED_APPLICANT_DATA_LOADED = "BLOCKED_APPLICANT_DATA_LOADED";
export const BLOCKED_APPLICANT_DATA_FAILED = "BLOCKED_APPLICANT_DATA_FAILED";

export const DELETED_DRIVER_DATA_LOADING = "DELETED_DRIVER_DATA_LOADING";
export const DELETED_DRIVER_DATA_LOADED = "DELETED_DRIVER_DATA_LOADED";
export const DELETE_DRIVER_DATA_FAILED = "DELETE_DRIVER_DATA_FAILED";

export const PERM_DELETED_DATA_LOADING = "PERM_DELETED_DATA_LOADING";
export const PERM_DELETED_DATA_LOADED = "PERM_DELETED_DATA_LOADED";
export const PERM_DELETED_DATA_FAILED = "PERM_DELETED_DATA_FAILED";

// coupon
export const REVIEW_REQUIRED_COUPON_DATA_FAILED =
  "REVIEW_REQUIRED_COUPON_DATA_FAILED";
export const REVIEW_REQUIRED_COUPON_DATA_LOADED =
  "REVIEW_REQUIRED_COUPON_DATA_LOADED";
export const REVIEW_REQUIRED_COUPON_DATA_LOADING =
  "REVIEW_REQUIRED_COUPON_DATA_LOADING";

// export const INVOICE_DATA_LOADING = "INVOICE_DATA_LOADING";
// export const INVOICE_DATA_LOADED = "INVOICE_DATA_LOADED";
// export const INVOICE_DATA_FAILED = "INVOICE_DATA_FAILED";

export const CREATE_RIDER_REFERRAL_FAILED = "CREATE_RIDER_REFERRAL_FAILED";
export const CREATE_RIDER_REFERRAL_LOADED = "CREATE_RIDER_REFERRAL_LOADED";
export const CREATE_RIDER_REFERRAL_LOADING = "CREATE_RIDER_REFERRAL_LOADING";
export const CLEAR_REDUCER_RIDER_REFERRAL = "CLEAR_REDUCER_RIDER_REFERRAL";

export const CREATE_DRIVER_REFERRAL_FAILED = "CREATE_DRIVER_REFERRAL_FAILED";
export const CREATE_DRIVER_REFERRAL_LOADED = "CREATE_DRIVER_REFERRAL_LOADED";
export const CREATE_DRIVER_REFERRAL_LOADING = "CREATE_DRIVER_REFERRAL_LOADING";
export const CLEAR_REDUCER_DRIVER_REFERRAL = "CLEAR_REDUCER_DRIVER_REFERRAL";

// coupon
export const CREATE_RIDER_COUPON_FAILED = "CREATE_RIDER_COUPON_FAILED";
export const CREATE_RIDER_COUPON_LOADED = "CREATE_RIDER_COUPON_LOADED";
export const CREATE_RIDER_COUPON_LOADING = "CREATE_RIDER_COUPON_LOADING";
export const CLEAR_REDUCER_RIDER_COUPON = "CLEAR_REDUCER_RIDER_COUPON";

export const CREATE_DRIVER_COUPON_FAILED = "CREATE_DRIVER_COUPON_FAILED";
export const CREATE_DRIVER_COUPON_LOADED = "CREATE_DRIVER_COUPON_LOADED";
export const CREATE_DRIVER_COUPON_LOADING = "CREATE_DRIVER_COUPON_LOADING";
export const CLEAR_REDUCER_DRIVER_COUPON = "CLEAR_REDUCER_DRIVER_COUPON";

export const MANAGE_DRIVER_DATA_LOADING = "MANAGE_DRIVER_DATA_LOADING";
export const MANAGE_DRIVER_DATA_LOADED = "MANAGE_DRIVER_DATA_LOADED";
export const MANAGE_DRIVER_DATA_FAILED = "MANAGE_DRIVER_DATA_FAILED";

export const DELETE_INCENTIVE_DATA = "DELETE_INCENTIVE_DATA";

export const PERMISSION_TYPE = "PERMISSION_TYPE";
