export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const RESET_ADMIN_PASSWORD = "RESET_ADMIN_PASSWORD";
export const RESET_LOGOUT_ADMIN_PASSWORD = "RESET_LOGOUT_ADMIN_PASSWORD";
// Dashboard
export const DASHBOARD_DEATILS = "DASHBOARD_DEATILS";
export const DASHBOARD_GRAPH_DEATILS = "DASHBOARD_GRAPH_DEATILS";
export const DASHBOARD_MORE_GRAPH_DEATILS = "DASHBOARD_MORE_GRAPH_DEATILS";
/********** Manage Admins ******/

export const DROPDOWN_LIST = "DROPDOWN_LIST";
export const BLOCKED_DROPDOWN_LIST = "BLOCKED_DROPDOWN_LIST";
export const DELETED_DROPDOWN_LIST = "DELETED_DROPDOWN_LIST";
export const ADD_ADMIN = "ADD_ADMIN";
export const ADMIN_LIST = "ADMIN_LIST";
export const ADMIN_FIND_ONE = "ADMIN_FIND_ONE";
export const VIEW_ADMIN = "VIEW_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const BLOCK_ADMIN_LIST = "BLOCK_ADMIN_LIST";
export const BLOCKED_ADMIN_EDIT = "BLOCKED_ADMIN_EDIT";
export const BLOCK_ADMIN = "BLOCK_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const UNBLOCK_ADMIN = "UNBLOCK_ADMIN";
export const DELETED_ADMIN_LIST = "DELETED_ADMIN_LIST";

/*************Manage Riders ************/
export const RIDER_LIST = "RIDER_LIST";
export const RIDER_VIEW = "RIDER_VIEW";
export const RIDER_HISTORY_VIEW = "RIDER_HISTORY_VIEW";
export const BLOCKED_RIDER_HISTORY_VIEW = "BLOCKED_RIDER_HISTORY_VIEW";
export const DELETED_RIDER_HISTORY_VIEW = "DELETED_RIDER_HISTORY_VIEW";
export const RESET_RIDER_RATING = "RESET_RIDER_RATING";
export const RESET_RIDER_PICTURE = "RESET_RIDER_PICTURE";
export const ACTIVATE_RIDER = "ACTIVATE_RIDER";
export const BLOCK_RIDER = "BLOCK_RIDER";
export const DELETE_RIDER = "DELETE_RIDER";
export const BLOCKED_RIDER_LIST = "BLOCKED_RIDER_LIST";
export const BLOCKED_RIDER_VIEW = "BLOCKED_RIDER_VIEW";
export const UNBLOCK_RIDER = "UNBLOCK_RIDER";
export const DELETED_RIDER_LIST = "DELETED_RIDER_LIST";
export const DELETED_RIDER_VIEW = "DELETED_RIDER_VIEW";
export const RESTORE_RIDER = "RESTORE_RIDER";
export const PERMANENTLY_DELETE_RIDER = "PERMANENTLY_DELETE_RIDER";
export const PERMANENTLY_DELETE_RIDER_LIST = "PERMANENTLY_DELETE_RIDER_LIST";
export const PERMANENTLY_DELETE_RIDER_VIEW = "PERMANENTLY_DELETE_RIDER_VIEW";
export const RIDER_DROPDOWN_LIST = "RIDER_DROPDOWN_LIST";
export const BLOCKED_RIDER_DROPDOWN_LIST = "BLOCKED_RIDER_DROPDOWN_LIST";
export const DEL_RIDER_DROPDOWN_LIST = "DEL_RIDER_DROPDOWN_LIST";
export const PER_DEL_RIDER_DROPDOWN_LIST = "PER_DEL_RIDER_DROPDOWN_LIST";

/*************Manage Drivers ************/
export const DRIVER_DROPDOWN_LIST = "DRIVER_DROPDOWN_LIST";
export const PENDING_DROPDOWN_LIST = "PENDING_DROPDOWN_LIST";
export const BLOCKED_DRIVER_DROPDOWN_LIST = "BLOCKED_DRIVER_DROPDOWN_LIST";
export const BANNED_DRIVER_DROPDOWN_LIST = "BANNED_DRIVER_DROPDOWN_LIST";
export const REJECTED_DRIVER_DROPDOWN_LIST = "REJECTED_DRIVER_DROPDOWN_LIST";
export const EXPIRED_DOCUMENT_DROPDOWN_LIST = "EXPIRED_DOCUMENT_DROPDOWN_LIST";
export const DELETED_DRIVER_DROPDOWN_LIST = "DELETED_DRIVER_DROPDOWN_LIST";
export const PER_DELETED_DRIVER_DROPDOWN_LIST =
  "PER_DELETED_DRIVER_DROPDOWN_LIST";

export const DRIVER_LIST = "DRIVER_LIST";
export const DRIVER_VIEW = "DRIVER_VIEW";
export const DRIVER_PREMIUM_HISTORY = "DRIVER_PREMIUM_HISTORY";
export const DRIVER_PROFILE_READ = "DRIVER_PROFILE_READ";
export const DRIVER_PROFILE_EDIT = "DRIVER_PROFILE_EDIT";
export const DRIVER_VEHICLE_EDIT = "DRIVER_VEHICLE_EDIT";
export const APPROVE_DRIVER_ACCOUNT = "APPROVE_DRIVER_ACCOUNT";
export const REJECT_DRIVER_ACCOUNT = "REJECT_DRIVER_ACCOUNT";
export const BAN_DRIVER_ACCOUNT = "BAN_DRIVER_ACCOUNT";
export const BLOCK_DRIVER_ACCOUNT = "BLOCK_DRIVER_ACCOUNT";
export const DELETE_DRIVER_ACCOUNT = "DELETE_DRIVER_ACCOUNT";
export const PENDING_APPLICATION_LIST = "PENDING_APPLICATION_LIST";
export const PENDING_APPLICANT_VIEW = "PENDING_APPLICANT_VIEW";
export const PENDING_APPLICANT_READ = "PENDING_APPLICANT_READ";
export const PENDING_APPLICANT_EDIT = "PENDING_APPLICANT_EDIT";
export const PENDING_APPLICANT_VEHICLE_EDIT = "PENDING_APPLICANT_VEHICLE_EDIT";
export const PEND_BANK_DETAILS_EDIT = "PEND_BANK_DETAILS_EDIT";
export const PEND_ADDRESS_PROOF_EDIT = "PEND_ADDRESS_PROOF_EDIT";
export const UPLOAD_ADRESS_PROOF = "UPLOAD_ADRESS_PROOF";
export const PEND_ADDRESS_PROOF_APPROVE = "PEND_ADDRESS_PROOF_APPROVE";
export const PEND_DL_EDIT = "PEND_DL_EDIT";
export const UPLOAD_DL = "UPLOAD_DL";
export const PEND_DL_APPROVE = "PEND_DL_APPROVE";
export const PEND_RC_EDIT = "PEND_RC_EDIT";
export const UPLOAD_RC = "UPLOAD_RC";
export const PEND_RC_APPROVE = "PEND_RC_APPROVE";
export const PEND_VEHICLE_INSURANCE_EDIT = "PEND_VEHICLE_INSURANCE_EDIT";
export const PEND_VEHICLE_INSURANCE_APPROVE = "PEND_VEHICLE_INSURANCE_APPROVE";
export const UPLOAD_INSURANCE = "UPLOAD_INSURANCE";

export const PEND_PROFILE_PIC_EDIT = "PEND_PROFILE_PIC_EDIT";
export const PEND_PROFILE_PIC_APPROVE = "PEND_PROFILE_PIC_APPROVE";
export const UPLOAD_PROFILE_PIC = "UPLOAD_PROFILE_PIC";
export const VEHICLE_PIC = "VEHICLE_PIC";
export const VEHICLE_PIC_EDIT = "VEHICLE_PIC_EDIT";
export const VEHICLE_PIC_APPROVE = "VEHICLE_PIC_APPROVE";
export const PEND_BG_VERIF_EDIT = "PEND_BG_VERIF_EDIT";
export const BG_VERIF_PIC = "BG_VERIF_PIC";
export const PEND_BG_VERIF_APPROVE = "PEND_BG_VERIF_APPROVE";
export const PEND_PHY_VERIF_EDIT = "PEND_PHY_VERIF_EDIT";
export const PHY_VERIF_PIC = "PHY_VERIF_PIC";
export const PEND_PHY_VERIF_APPROVE = "PEND_PHY_VERIF_APPROVE";
export const REJECTED_APPLICATION_LIST = "REJECTED_APPLICATION_LIST";
export const REJECTED_APPLICANT_VIEW = "REJECTED_APPLICANT_VIEW";
export const REJECT_APPLICANT_READ = "REJECT_APPLICANT_READ";
export const BLOCKED_APPLICATION_LIST = "BLOCKED_APPLICATION_LIST";
export const BLOCKED_APPLICANT_VIEW = "BLOCKED_APPLICANT_VIEW";
export const UNBLOCK_DRIVER = "UNBLOCK_DRIVER";

export const BLOCKED_BANK_DETAILS_EDIT = "BLOCKED_BANK_DETAILS_EDIT";
export const BLOCKED_ADDRESS_PROOF_EDIT = "BLOCKED_ADDRESS_PROOF_EDIT";
export const BLOCKED_DL_EDIT = "BLOCKED_DL_EDIT";
export const BLOCKED_PROFILE_PIC_EDIT = "BLOCKED_PROFILE_PIC_EDIT";
export const BLOCKED_BG_VERIF_EDIT = "BLOCKED_BG_VERIF_EDIT";
export const BLOCKED_VI_EDIT = "BLOCKED_VI_EDIT";
export const BLOCKED_RC_EDIT = "BLOCKED_RC_EDIT";
export const BLOCKED_VEHICLE_IMAGE_EDIT = "BLOCKED_VEHICLE_IMAGE_EDIT";
export const BLOCKED_PHY_VERIF_EDIT = "BLOCKED_PHY_VERIF_EDIT";

export const BLOCKED_APPLICANT_READ = "BLOCKED_APPLICANT_READ";
export const BANNED_APPLICATION_LIST = "BANNED_APPLICATION_LIST";
export const BANNED_APPLICANT_VIEW = "BANNED_APPLICANT_VIEW";
export const BANEED_APPLICANT_READ = "BANEED_APPLICANT_READ";

// image upload coupon
export const IMAGE_UPLOAD_COUPON = "IMAGE_UPLOAD_COUPON";

export const REJECT_BANK_DETAILS_EDIT = "REJECT_BANK_DETAILS_EDIT";
export const REJECT_ADDRESS_PROOF_EDIT = "REJECT_ADDRESS_PROOF_EDIT";
export const REJECT_DL_EDIT = "REJECT_DL_EDIT";
export const REJECT_PROFILE_PIC_EDIT = "REJECT_PROFILE_PIC_EDIT";
export const REJECT_BG_VERIF_EDIT = "REJECT_BG_VERIF_EDIT";
export const REJECT_VI_EDIT = "REJECT_VI_EDIT";
export const REJECT_RC_EDIT = "REJECT_RC_EDIT";
export const REJECT_VEHICLE_IMAGE_EDIT = "REJECT_VEHICLE_IMAGE_EDIT";
export const REJECT_PHY_VERIF_EDIT = "REJECT_PHY_VERIF_EDIT";

export const DRIVER_BANK_DETAILS_EDIT = "DRIVER_BANK_DETAILS_EDIT";
export const DRIVER_ADDRESS_PROOF_EDIT = "DRIVER_ADDRESS_PROOF_EDIT";
export const DRIVER_DL_EDIT = "DRIVER_DL_EDIT";
export const DRIVER_PROFILE_PIC_EDIT = "DRIVER_PROFILE_PIC_EDIT";
export const DRIVER_BG_VERIF_EDIT = "DRIVER_BG_VERIF_EDIT";
export const DRIVER_VI_EDIT = "DRIVER_VI_EDIT";
export const DRIVER_RC_EDIT = "DRIVER_RC_EDIT";
export const DRIVER_VEHICLE_IMAGE_EDIT = "DRIVER_VEHICLE_IMAGE_EDIT";
export const DRIVER_PHY_VERIF_EDIT = "DRIVER_PHY_VERIF_EDIT";
export const MANAGE_DRIVER_MAIN_ZONE_LIST = "MANAGE_DRIVER_MAIN_ZONE_LIST";
export const MANAGE_DRIVER_VEHICLE_COLOR_LIST =
  "MANAGE_DRIVER_VEHICLE_COLOR_LIST";
export const MANAGE_DRIVER_RIDETYPE_LIST = "MANAGE_DRIVER_RIDETYPE_LIST";
export const MANAGE_DRIVER_VEHICLETYPE_LIST = "MANAGE_DRIVER_VEHICLETYPE_LIST";
export const VEHICLETYPE_MODEL_COLOR_LIST = "VEHICLETYPE_MODEL_COLOR_LIST";
export const DRIVER_PREMIUM_LIST_ACTION = "DRIVER_PREMIUM_LIST_ACTION";
export const DRIVER_ACTIVATE_AUTO_RENEW = "DRIVER_ACTIVATE_AUTO_RENEW";
export const DRIVER_CANCEL_AUTO_RENEW = "DRIVER_CANCEL_AUTO_RENEW";
export const DRIVER_CANCEL_ACTIVE_AUTO_RENEW =
  "DRIVER_CANCEL_ACTIVE_AUTO_RENEW";

export const EXPIRED_APPLICATION_LIST = "EXPIRED_APPLICATION_LIST";
export const EXPIRED_APPLICATION_VIEW = "EXPIRED_APPLICATION_VIEW";
export const EXPIRED_APPLICANT_VIEW = "EXPIRED_APPLICANT_VIEW";
export const EXPIRED_PROFILE_READ = "EXPIRED_PROFILE_READ";
export const EXPIRED_BANK_DETAILS_EDIT = "EXPIRED_BANK_DETAILS_EDIT";
export const EXPIRED_ADDRESS_PROOF_EDIT = "EXPIRED_ADDRESS_PROOF_EDIT";
export const EXPIRED_DL_EDIT = "EXPIRED_DL_EDIT";
export const EXPIRED_PROFILE_PIC_EDIT = "EXPIRED_PROFILE_PIC_EDIT";
export const EXPIRED_BG_VERIF_EDIT = "EXPIRED_BG_VERIF_EDIT";
export const EXPIRED_VI_EDIT = "EXPIRED_VI_EDIT";
export const EXPIRED_RC_EDIT = "EXPIRED_RC_EDIT";
export const EXPIRED_VEHICLE_IMAGE_EDIT = "EXPIRED_VEHICLE_IMAGE_EDIT";
export const EXPIRED_PHY_VERIF_EDIT = "EXPIRED_PHY_VERIF_EDIT";

export const DELETED_DRIVER_LIST = "DELETED_DRIVER_LIST";
export const DELETED_DRIVER_VIEW = "DELETED_DRIVER_VIEW";
export const DELETED_DRIVER_PROFILE_READ = "DELETED_DRIVER_PROFILE_READ";
export const DELETE_ACCOUNT_PERMANENTLTY = "DELETE_ACCOUNT_PERMANENTLTY";
export const RESTORE_DRIVER = "RESTORE_DRIVER";
export const PERMANENT_DELETED_DRIVER_LIST = "PERMANENT_DELETED_DRIVER_LIST";
export const PERMANENT_DELETED_DRIVER_VIEW = "PERMANENT_DELETED_DRIVER_VIEW";
export const PERMANENT_DELETED_DRIVER_READ = "PERMANENT_DELETED_DRIVER_READ";

/*************Manage Fares ************/
/**************Manage fares-Default fare ********/
export const EDIT_LOCAL_DEFAULT_FARE = "EDIT_LOCAL_DEFAULT_FARE";
export const LOCAL_DEFAULT_FARE_VALUE = "LOCAL_DEFAULT_FARE_VALUE";
export const EDIT_SPECIAL_ZONE_FARE = "EDIT_SPECIAL_ZONE_FARE";
export const SPECIAL_ZONE_FARE_VALUE = "SPECIAL_ZONE_FARE_VALUE";
export const EDIT_RENTAL_FARE = "EDIT_RENTAL_FARE";
export const RENTAL_FARE_VALUE = "RENTAL_FARE_VALUE";
export const TOLLS_FARE_VALUE = "TOLLS_FARE_VALUE";
export const EDIT_TOLLS_FARE = "EDIT_TOLLS_FARE";
export const ONEWAY_TRIP_FARE_VALUE = "ONEWAY_TRIP_FARE_VALUE";
export const EDIT_ONEWAY_TRIP_FARE = "EDIT_ONEWAY_TRIP_FARE";
export const EDIT_ONEWAY_PACKAGE_DETAILS = "EDIT_ONEWAY_PACKAGE_DETAILS";
export const ROUND_TRIP_FARE_VALUE = "ROUND_TRIP_FARE_VALUE";
export const EDIT_ROUND_TRIP_FARE = "EDIT_ROUND_TRIP_FARE";
export const EDIT_ROUND_TRIP_PACKAGE_DETAILS =
  "EDIT_ROUND_TRIP_PACKAGE_DETAILS";
export const DEFAULT_RIDE_TYPE_LIST = "DEFAULT_RIDE_TYPE_LIST";
/**************Manage fares-Manage fare ********/
export const MANAGE_FARES_LIST = "MANAGE_FARES_LIST";
export const FARES_SPECIAL_ZONE_LIST = "FARES_SPECIAL_ZONE_LIST";
export const FARES_SPECIAL_ZONE_INDIVIDUAL = "FARES_SPECIAL_ZONE_INDIVIDUAL";
export const FARES_SPECIAL_ZONE_INDIVIDUAL_EDIT =
  "FARES_SPECIAL_ZONE_INDIVIDUAL_EDIT";

export const FARES_TOLLS_ZONE_LIST = "FARES_TOLLS_ZONE_LIST";
export const FARES_TOLLS_ZONE_INDIVIDUAL = "FARES_TOLLS_ZONE_INDIVIDUAL";
export const FARES_TOLLS_ZONE_INDIVIDUAL_EDIT =
  "FARES_TOLLS_ZONE_INDIVIDUAL_EDIT";
export const FARES_ONEWAY_TRIP_LIST = "FARES_ONEWAY_TRIP_LIST";
export const FARES_ONEWAY_TRIP_INDIVIDUAL = "FARES_ONEWAY_TRIP_INDIVIDUAL";
export const FARES_ONEWAY_TRIP_INDIVIDUAL_EDIT =
  "FARES_ONEWAY_TRIP_INDIVIDUAL_EDIT";
export const FARES_ONEWAY_TRIP_PACKAGE_EDIT = "FARES_ONEWAY_TRIP_PACKAGE_EDIT";
export const FARES_LOCAL_ZONE_DROPDOWN_LIST = "FARES_LOCAL_ZONE_DROPDOWN_LIST";
export const LOCAL_CREATE_FARES = "LOCAL_CREATE_FARES";
export const FARES_LOCAL_ZONES_LIST = "FARES_LOCAL_ZONES_LIST";
export const FARES_LOCAL_ZONE_INDIVIDUAL = "FARES_LOCAL_ZONE_INDIVIDUAL";
export const FARES_LOCAL_UPDATE_PRICING_MODULE =
  "FARES_LOCAL_UPDATE_PRICING_MODULE";
export const FARES_LOCAL_UPDATE_PRICING_DETAILS =
  "FARES_LOCAL_UPDATE_PRICING_DETAILS";
export const FARES_ROUND_TRIP_LIST = "FARES_ROUND_TRIP_LIST";
export const FARES_ROUND_TRIP_INDIVIDUAL = "FARES_ROUND_TRIP_INDIVIDUAL";
export const FARES_ROUND_TRIP_INDIVIDUAL_EDIT =
  "FARES_ROUND_TRIP_INDIVIDUAL_EDIT";
export const FARES_ROUND_TRIP_PACKAGE_EDIT = "FARES_ROUND_TRIP_PACKAGE_EDIT";
export const FARES_RENTAL_LIST = "FARES_RENTAL_LIST";
export const FARES_RENTAL_INDIVIDUAL = "FARES_RENTAL_INDIVIDUAL";
export const FARES_RENTAL_INDIVIDUAL_EDIT = "FARES_RENTAL_INDIVIDUAL_EDIT";
export const ZONE_STATUS_CHANGE = "ZONE_STATUS_CHANGE";
export const CREATE_RENTAL_PACKAGE = "CREATE_RENTAL_PACKAGE";
export const DELETE_RENTAL_PACKAGE = "DELETE_RENTAL_PACKAGE";
export const MANAGE_FARES_DRP_DWN = "MANAGE_FARES_DRP_DWN";
/**************Manage fares-Deleted intra fare ********/
export const DELETED_INTRA_FARES_LIST = "DELETED_INTRA_FARES_LIST";
export const DELETED_INTRA_FARES_LOCAL_LIST = "DELETED_INTRA_FARES_LOCAL_LIST";
export const DELETED_INTRA_FARES_LOCAL_INDIVIDUAL_LIST =
  "DELETED_INTRA_FARES_LOCAL_INDIVIDUAL_LIST";
export const DELETED_INTRA_FARES_SPECIAL_LIST =
  "DELETED_INTRA_FARES_SPECIAL_LIST";
export const DELETED_INTRA_FARES_TOLL_LIST = "DELETED_INTRA_FARES_TOLL_LIST";
export const DELETED_INTRA_FARES_ONE_WAY_LIST =
  "DELETED_INTRA_FARES_ONE_WAY_LIST";
export const DELETED_INTRA_FARES_INDIVIDUAL = "DELETED_INTRA_FARES_INDIVIDUAL";

export const ARCH_DEL_INTRA_FARES_LOCAL_LIST =
  "ARCH_DEL_INTRA_FARES_LOCAL_LIST";
export const ARCH_DEL_INTRA_FARES_LOCAL_IND_LIST =
  "ARCH_DEL_INTRA_FARES_LOCAL_IND_LIST";
export const ARCH_DEL_INTRA_FARES_SPECIAL_LIST =
  "ARCH_DEL_INTRA_FARES_SPECIAL_LIST";
export const ARCH_DEL_INTRA_FARES_TOLL_LIST = "ARCH_DEL_INTRA_FARES_TOLL_LIST";
export const ARCH_DEL_INTRA_FARES_ONE_WAY_LIST =
  "ARCH_DEL_INTRA_FARES_ONE_WAY_LIST";
export const ARCH_DEL_INTRA_FARES_INDIVIDUAL =
  "ARCH_DEL_INTRA_FARES_INDIVIDUAL";
/**************Manage fares-Archived fare ********/
export const ARCHIVED_FARES_LIST = "ARCHIVED_FARES_LIST";
export const ARCHIVED_FARES_SPECIAL_ZONE_LIST =
  "ARCHIVED_FARES_SPECIAL_ZONE_LIST";
export const ARCHIVED_FARES_SPECIAL_ZONE_INDIVIDUAL =
  "ARCHIVED_FARES_SPECIAL_ZONE_INDIVIDUAL";

export const ARCHIVED_FARES_TOLLS_ZONE_LIST = "ARCHIVED_FARES_TOLLS_ZONE_LIST";
export const ARCHIVED_FARES_TOLLS_ZONE_INDIVIDUAL =
  "ARCHIVED_FARES_TOLLS_ZONE_INDIVIDUAL";

export const ARCHIVED_FARES_ONEWAY_TRIP_LIST =
  "ARCHIVED_FARES_ONEWAY_TRIP_LIST";
export const ARCHIVED_FARES_ONEWAY_TRIP_INDIVIDUAL =
  "ARCHIVED_FARES_ONEWAY_TRIP_INDIVIDUAL";

export const ARCHIVED_FARES_LOCAL_ZONE_DROPDOWN_LIST =
  "ARCHIVED_FARES_LOCAL_ZONE_DROPDOWN_LIST";
export const LOCAL_CREATE_ARCHIVED_FARES = "LOCAL_CREATE_ARCHIVED_FARES";
export const ARCHIVED_FARES_LOCAL_ZONES_LIST =
  "ARCHIVED_FARES_LOCAL_ZONES_LIST";
export const ARCHIVED_FARES_LOCAL_ZONE_INDIVIDUAL =
  "ARCHIVED_FARES_LOCAL_ZONE_INDIVIDUAL";

export const ARCHIVED_FARES_ROUND_TRIP_LIST = "ARCHIVED_FARES_ROUND_TRIP_LIST";
export const ARCHIVED_FARES_ROUND_TRIP_INDIVIDUAL =
  "ARCHIVED_FARES_ROUND_TRIP_INDIVIDUAL";

export const ARCHIVED_FARES_RENTAL_LIST = "ARCHIVED_FARES_RENTAL_LIST";
export const ARCHIVED_FARES_RENTAL_INDIVIDUAL =
  "ARCHIVED_FARES_RENTAL_INDIVIDUAL";
export const ARCHIVED_DELETED_INTRA_FARES_LIST =
  "ARCHIVED_DELETED_INTRA_FARES_LIST";

// **************** refund *****************

export const PENDING_REFUND_LIST = "PENDING_REFUND_LIST";
export const PENDING_REFUND_VIEW = "PENDING_REFUND_VIEW";
export const PENDING_REFUND_UPDATE = "PENDING_REFUND_UPDATE";
export const SUCCESSFUL_REFUND_LIST = "SUCCESSFUL_REFUND_LIST";
export const SUCCESSFUL_REFUND_VIEW = "SUCCESSFUL_REFUND_VIEW";
export const CANCELLED_REFUND_LIST = "CANCELLED_REFUND_LIST";
export const CANCELLED_REFUND_VIEW = "CANCELLED_REFUND_VIEW";
export const SUCES_REF_DRP_DWN = "SUCES_REF_DRP_DWN";
export const CANCEL_REF_DRP_DWN = "CANCEL_REF_DRP_DWN";
export const PEND_REF_DRP_DWN = "PEND_REF_DRP_DWN";

// ***************ridetype/vehicle************

export const ADD_RIDETYPE = "ADD_RIDETYPE";
export const RIDETYPE_ZONE_LIST = "RIDETYPE_ZONE_LIST";
export const RIDETYPE_LIST = "RIDETYPE_LIST";
export const RIDETYPE_VIEW = "RIDETYPE_VIEW";
export const EDIT_RIDETYPE = "EDIT_RIDETYPE";
export const VEHICLETYPE_LIST = "VEHICLETYPE_LIST";
export const ADD_VEHICLETYPE = "ADD_VEHICLETYPE";
export const RIDETYPE_DROPDOWN = "RIDETYPE_DROPDOWN";
export const VEHICLETYPE_VIEW = "VEHICLETYPE_VIEW";
export const VEHICLETYPE_EDIT = "VEHICLETYPE_EDIT";
export const IMAGE_UPLOAD_RIDETYPE = "IMAGE_UPLOAD_RIDETYPE";
export const RIDETYPE_DROPDOWN_LIST = "RIDETYPE_DROPDOWN_LIST";
export const DELETE_RIDETYPE = "DELETE_RIDETYPE";
export const VEHICLETYPE_DROPDOWN_LIST = "VEHICLETYPE_DROPDOWN_LIST";

/*************Manage booking Request ***********/

export const ONGOING_REQUEST_LIST = "ONGOING_REQUEST_LIST";
export const ONGOING_REQUEST_INDIVIDUAL = "ONGOING_REQUEST_INDIVIDUAL";
export const UNSUCCESSFULL_REQUEST_LIST = "UNSUCCESSFULL_REQUEST_LIST";
export const UNSUCCESSFULL_REQUEST_INDIVIDUAL =
  "UNSUCCESSFULL_REQUEST_INDIVIDUAL";
export const ONGOING_DROPDOWN_LIST = "ONGOING_DROPDOWN_LIST";
export const UNSUCCESSFUL_DROPDOWN_LIST = "UNSUCCESSFUL_DROPDOWN_LIST";

/*************Manage booking ***********/

export const ONGOING_BOOKING_LIST = "ONGOING_BOOKING_LIST";
export const ONGOING_BOOKING_INDIVIDUAL = "ONGOING_BOOKING_INDIVIDUAL";
export const ONGOING_DRIVER_REQ_CANCEL = "ONGOING_DRIVER_REQ_CANCEL";
export const ONGOING_RIDER_REQ_CANCEL = "ONGOING_RIDER_REQ_CANCEL";
export const ONGOING_ACCIDENT_REPORTED = "ONGOING_ACCIDENT_REPORTED";
export const ONGOING_END_TRIP = "ONGOING_END_TRIP";
export const ONGOING_UPDATE_PaymentMethod = "ONGOING_UPDATE_PaymentMethod";
export const ONGOING_UPDATE_BILLING_DETAILS = "ONGOING_UPDATE_BILLING_DETAILS";
export const ONGOING_UPDATE_INITIAL_ODOMETER =
  "ONGOING_UPDATE_INITIAL_ODOMETER";
export const ONGOING_UPDATE_FINAL_ODOMETER = "ONGOING_UPDATE_FINAL_ODOMETER";
export const COMPLETED_BOOKING_LIST = "COMPLETED_BOOKING_LIST";
export const COMPLETED_BOOKING_INDIVIDUAL = "COMPLETED_BOOKING_INDIVIDUAL";
export const COMPLETED_UPDATE_PaymentMethod = "COMPLETED_UPDATE_PaymentMethod";
export const COMPLETED_UPDATE_BILLING_DETAILS =
  "COMPLETED_UPDATE_BILLING_DETAILS";
export const COMPLETED_UPDATE_INITIAL_ODOMETER =
  "COMPLETED_UPDATE_INITIAL_ODOMETER";
export const COMPLETED_UPDATE_FINAL_ODOMETER =
  "COMPLETED_UPDATE_FINAL_ODOMETER";
export const COMPLETED_BOOKING_CREATE_REFUND =
  "COMPLETED_BOOKING_CREATE_REFUND";
export const COMPLETED_BOOKING_CANCEL_REFUND =
  "COMPLETED_BOOKING_CANCEL_REFUND";
export const COMPLETED_BOOKING_CANCEL_DRIVER_FINE =
  "COMPLETED_BOOKING_CANCEL_DRIVER_FINE";
export const CANCELLED_BOOKING_LIST = "CANCELLED_BOOKING_LIST";
export const CANCELLED_BOOKING_INDIVIDUAL = "CANCELLED_BOOKING_INDIVIDUAL";
export const CANCELLED_UPDATE_PaymentMethod = "CANCELLED_UPDATE_PaymentMethod";
export const CANCELLED_UPDATE_BILLING_DETAILS =
  "CANCELLED_UPDATE_BILLING_DETAILS";
export const CANCELLED_UPDATE_INITIAL_ODOMETER =
  "CANCELLED_UPDATE_INITIAL_ODOMETER";
export const CANCELLED_UPDATE_FINAL_ODOMETER =
  "CANCELLED_UPDATE_FINAL_ODOMETER";
export const CANCELLED_BOOKING_CREATE_REFUND =
  "CANCELLED_BOOKING_CREATE_REFUND";
export const CANCELLED_BOOKING_CANCEL_REFUND =
  "CANCELLED_BOOKING_CANCEL_REFUND";
export const CANCELLED_BOOKING_CANCEL_DRIVER_FINE =
  "CANCELLED_BOOKING_CANCEL_DRIVER_FINE";
export const ACCIDENT_BOOKING_LIST = "ACCIDENT_BOOKING_LIST";
export const ACCIDENT_BOOKING_INDIVIDUAL = "ACCIDENT_BOOKING_INDIVIDUAL";
export const ACCIDENT_UPDATE_BILLING_DETAILS =
  " ACCIDENT_UPDATE_BILLING_DETAILS";
export const ACCIDENT_UPDATE_INITIAL_ODOMETER =
  "ACCIDENT_UPDATE_INITIAL_ODOMETER";
export const ACCIDENT_UPDATE_FINAL_ODOMETER = "ACCIDENT_UPDATE_FINAL_ODOMETER";
export const ACCIDENT_UPDATE_PaymentMethod = "ACCIDENT_UPDATE_PaymentMethod";
export const ACCIDENT_BOOKING_CREATE_REFUND = "ACCIDENT_BOOKING_CREATE_REFUND";
export const ACCIDENT_BOOKING_CANCEL_REFUND = "ACCIDENT_BOOKING_CANCEL_REFUND";
export const ACCIDENT_BOOKING_CANCEL_DRIVER_FINE =
  "ACCIDENT_BOOKING_CANCEL_DRIVER_FINE";
export const ADJUSTED_BOOKING_LIST = "ADJUSTED_BOOKING_LIST";
export const ADJUSTED_BOOKING_INDIVIDUAL = "ADJUSTED_BOOKING_INDIVIDUAL";
export const ACCIDENT_BOOKINGS_DROPDOWN_LIST =
  "ACCIDENT_BOOKINGS_DROPDOWN_LIST";
export const ADJUSTED_BOOKINGS_DROPDOWN_LIST =
  "ADJUSTED_BOOKINGS_DROPDOWN_LIST";
export const CANCELLED_BOOKINGS_DROPDOWN_LIST =
  "CANCELLED_BOOKINGS_DROPDOWN_LIST";
export const COMPLETED_BOOKINGS_DROPDOWN_LIST =
  "COMPLETED_BOOKINGS_DROPDOWN_LIST";
export const ONGOING_BOOKINGS_DROPDOWN_LIST = "ONGOING_BOOKINGS_DROPDOWN_LIST";

export const TRIP_INVOICE_LIST = "TRIP_INVOICE_LIST";
export const TRIP_INVOICE = "TRIP_INVOICE";
export const TRIP_INVOICE_DROPDOWN_LIST = "TRIP_INVOICE_DROPDOWN_LIST";

/*************Manage zones ***********/

export const MANAGE_ZONES_LIST = "MANAGE_ZONES_LIST";
export const MAIN_ZONE_VIEW = "MAIN_ZONE_VIEW";
export const FIND_ALL_COORDINATES = "FIND_ALL_COORDINATES";
export const ADD_MAIN_ZONE = "ADD_MAIN_ZONE";
export const EDIT_MAIN_ZONE = "EDIT_MAIN_ZONE";
export const LOCAL_ZONE_LIST = "LOCAL_ZONE_LIST";
export const ADD_LOCAL_ZONES = "ADD_LOCAL_ZONES";
export const LOCAL_ZONE_VIEW = "LOCAL_ZONE_VIEW";
export const UPDATE_LOCAL_ZONES = "UPDATE_LOCAL_ZONES";
export const DELETE_LOCAL_ZONES = "DELETE_LOCAL_ZONES";
export const SPECIAL_ZONE_LIST = "SPECIAL_ZONE_LIST";
export const ADD_SPECIAL_ZONES = "ADD_SPECIAL_ZONES";
export const SPECIAL_ZONE_VIEW = "SPECIAL_ZONE_VIEW";
export const UPDATE_SPECIAL_ZONES = "UPDATE_SPECIAL_ZONES";
export const DELETE_SPECIAL_ZONES = "DELETE_SPECIAL_ZONES";
export const TOLLS_ZONE_LIST = "TOLLS_ZONE_LIST";
export const ADD_TOLLS_ZONES = "ADD_TOLLS_ZONES";
export const TOLLS_ZONE_VIEW = "TOLLS_ZONE_VIEW";
export const UPDATE_TOLLS_ZONES = "UPDATE_TOLLS_ZONES";
export const DELETE_TOLLS_ZONES = "DELETE_TOLLS_ZONES";
export const OUTSTATION_ZONE_LIST = "OUTSTATION_ZONE_LIST";
export const ADD_OUTSTATION_ZONES = "ADD_OUTSTATION_ZONES";
export const OUTSTATION_ZONE_VIEW = "OUTSTATION_ZONE_VIEW";
export const UPDATE_OUTSTATION_ZONES = "UPDATE_OUTSTATION_ZONES";
export const DELETE_OUTSTATION_ZONES = "DELETE_OUTSTATION_ZONES";
export const ARCHIVE_ZONES_LIST = "ARCHIVE_ZONES_LIST";
export const ADD_ARCHIVE_ZONE = "ADD_ARCHIVE_ZONE";
export const ARCHIVE_ZONE_VIEW = "ARCHIVE_ZONE_VIEW";
export const RESTORE_ARCHIVE_ZONE = "RESTORE_ARCHIVE_ZONE";
export const BLOCKED_ZONES_LIST = "BLOCKED_ZONES_LIST";
export const ADD_BLOCKED_ZONE = "ADD_BLOCKED_ZONE";
export const UPDATE_BLOCK_ZONE = "UPDATE_BLOCK_ZONE";
export const BLOCKED_ZONE_VIEW = "BLOCKED_ZONE_VIEW";
export const UNBLOCK_ZONE = "UNBLOCK_ZONE";
export const DELETED_INTRA_ZONES_LIST = "DELETED_INTRA_ZONES_LIST";
export const RESTORE_LOCAL_INTRA_ZONES = "RESTORE_LOCAL_INTRA_ZONES";
export const RESTORE_SPECIAL_ZONE_INTRA_ZONES =
  "RESTORE_SPECIAL_ZONE_INTRA_ZONES";
export const RESTORE_OUTSTATION_INTRA_ZONES = "RESTORE_OUTSTATION_INTRA_ZONES";
export const RESTORE_TOLL_INTRA_ZONES = "RESTORE_TOLL_INTRA_ZONES";
export const DELETE_LOCAL_INTRA_ZONE_PERMANENTLY =
  "DELETE_LOCAL_INTRA_ZONE_PERMANENTLY";
export const DELETE_SPECIAL_ZONE_INTRA_ZONE_PERMANENTLY =
  "DELETE_SPECIAL_ZONE_INTRA_ZONE_PERMANENTLY";
export const DELETE_OUTSTATION_INTRA_ZONE_PERMANENTLY =
  "DELETE_OUTSTATION_INTRA_ZONE_PERMANENTLY";
export const DELETE_TOLL_INTRA_ZONE_PERMANENTLY =
  "DELETE_TOLL_INTRA_ZONE_PERMANENTLY";

export const MANAGE_ZONES_DRP_DWN = "MANAGE_ZONES_DRP_DWN";
export const ARCHIVE_ZONES_DRP_DWN = "ARCHIVE_ZONES_DRP_DWN";
export const BLOCKED_ZONES_DRP_DWN = "BLOCKED_ZONES_DRP_DWN";
export const DELETED_INTRA_ZONES_DRP_DWN = "DELETED_INTRA_ZONES_DRP_DWN";

/*****************Driver coupons  *********/

export const CREATE_DRIVER_COUPON = "CREATE_DRIVER_COUPON";
export const CREATE_DRIVER_COUPON_BROADCAST = "CREATE_DRIVER_COUPON_BROADCAST";
export const REVIEW_REQUIRED_DRIVER_COUPON_LIST =
  "REVIEW_REQUIRED_DRIVER_COUPON_LIST";
export const REVIEW_REQUIRED_DRIVER_COUPON = "REVIEW_REQUIRED_DRIVER_COUPON";
export const REVIEW_REQ_DRIVER_COUPON_LIST = "REVIEW_REQ_DRIVER_COUPON_LIST";
export const REVIEW_REQ_DRIVER_COUPON = "REVIEW_REQ_DRIVER_COUPON";
export const REVIEW_REQ_DRIVER_COUPON_EDIT = "REVIEW_REQ_DRIVER_COUPON_EDIT";
export const APPROVE_DRIVER_COUPON = "APPROVE_DRIVER_COUPON";
export const REJECT_DRIVER_COUPON = "REJECT_DRIVER_COUPON";

export const ACTIVE_DRIVER_COUPON_LIST = "ACTIVE_DRIVER_COUPON_LIST";
export const ACTIVE_DRIVER_COUPON = "ACTIVE_DRIVER_COUPON";
export const ACTIVE_DRIVER_COUPON_EDIT = "ACTIVE_DRIVER_COUPON_EDIT";
export const ACTIVE_DRIVER_COUPON_BROADCAST_EDIT =
  "ACTIVE_DRIVER_COUPON_BROADCAST_EDIT";
export const REJECTED_DRIVER_COUPON_LIST = "REJECTED_DRIVER_COUPON_LIST";
export const REJECTED_DRIVER_COUPON = "REJECTED_DRIVER_COUPON";
export const DELETED_DRIVER_COUPON_LIST = "DELETED_DRIVER_COUPON_LIST";
export const DELETE_DRIVER_COUPON = "DELETE_DRIVER_COUPON";
export const DELETED_DRIVER_COUPON = "DELETED_DRIVER_COUPON";
export const EXPIRED_DRIVER_COUPON_LIST = "EXPIRED_DRIVER_COUPON_LIST";
export const EXPIRED_DRIVER_COUPON = "EXPIRED_DRIVER_COUPON";
export const DRIVER_COUPON_USAGE_HISTORY_LIST =
  "DRIVER_COUPON_USAGE_HISTORY_LIST";
export const DRIVER_COUPON_USAGE_HISTORY = "DRIVER_COUPON_USAGE_HISTORY";
export const DROPDOWNLIST_DRIVER_PENDING_COUPON =
  "DROPDOWNLIST_DRIVER_PENDING_COUPON";
export const DROPDOWNLIST_DRIVER_ACTIVE_COUPON =
  "DROPDOWNLIST_DRIVER_ACTIVE_COUPON";
export const DROPDOWNLIST_DRIVER_REJECTED_COUPON =
  "DROPDOWNLIST_DRIVER_REJECTED_COUPON";
export const DROPDOWNLIST_DRIVER_DELETED_COUPON =
  "DROPDOWNLIST_DRIVER_DELETED_COUPON";
export const DROPDOWNLIST_DRIVER_EXPIRED_COUPON =
  "DROPDOWNLIST_DRIVER_EXPIRED_COUPON";
export const DROPDOWNLIST_DRIVER_USAGE_COUPON =
  "DROPDOWNLIST_DRIVER_USAGE_COUPON";
// rider coupon

export const CREATE_GENERAL_ACTION = "CREATE_GENERAL_ACTION";
export const CREATE_NEW_ACCOUNT_ACTION = "CREATE_NEW_ACCOUNT_ACTION";
export const CREATE_NEW_ACCOUNT_LIFE_SPAN = "CREATE_NEW_ACCOUNT_LIFE_SPAN";
export const CREATE_PAYMENT_METHOD_ACTION = "CREATE_PAYMENT_METHOD_ACTION";
export const CREATE_BOOKING_DESTINATION_ACTION =
  "CREATE_BOOKING_DESTINATION_ACTION";
export const CREATE_PICKUP_DROPOFF_ACTION = "CREATE_PICKUP_DROPOFF_ACTION";
export const CREATE_RENTAL_PACKAGE_ACTION = "CREATE_RENTAL_PACKAGE_ACTION";
export const CREATE_BOOKING_DISTANCE_ACTION = "CREATE_BOOKING_DISTANCE_ACTION";
export const CREATE_OUTSTATION_PACKAGE_ACTION =
  "CREATE_OUTSTATION_PACKAGE_ACTION";
export const CLEAR_RIDER_COUPON = "CLEAR_RIDER_COUPON";
export const CLEAR_DRIVER_COUPON = "CLEAR_DRIVER_COUPON";
export const DROPDOWNLIST_RIDER_COUPON = "DROPDOWNLIST_RIDER_COUPON";
export const DROPDOWNLIST_RIDER_ACTIVE_COUPON =
  "DROPDOWNLIST_RIDER_ACTIVE_COUPON";
export const DROPDOWNLIST_RIDER_REJECTED_COUPON =
  "DROPDOWNLIST_RIDER_REJECTED_COUPON";
export const DROPDOWNLIST_RIDER_DELETED_COUPON =
  "DROPDOWNLIST_RIDER_DELETED_COUPON";
export const DROPDOWNLIST_RIDER_EXPIRED_COUPON =
  "DROPDOWNLIST_RIDER_EXPIRED_COUPON";
export const DROPDOWNLIST_RIDER_USAGE_COUPON =
  "DROPDOWNLIST_RIDER_USAGE_COUPON";
export const COUPON_RIDETYPE_LIST = "COUPON_RIDETYPE_LIST";

// zonelist

export const COUPON_MAIN_ZONE_LIST = "COUPON_MAIN_ZONE_LIST";
export const COUPON_LOCAL_ZONE_LIST = "COUPON_LOCAL_ZONE_LIST";
export const COUPON_SPECIAL_ZONE_LIST = "COUPON_SPECIAL_ZONE_LIST";
export const COUPON_OUTSTATION_ZONE_LIST = "COUPON_OUTSTATION_ZONE_LIST";

// send review
export const SEND_REVIEW_ACTION = "SEND_REVIEW_ACTION";
export const ACTIVE_COUPON_SEND_REVIEW = "ACTIVE_COUPON_SEND_REVIEW";

// pending coupon view
export const PENDING_COUPON_ALL_VIEW = "PENDING_COUPON_ALL_VIEW";
export const ACTIVE_COUPON_ALL_VIEW = "ACTIVE_COUPON_ALL_VIEW";
export const REJECTED_COUPON_ALL_VIEW = "REJECTED_COUPON_ALL_VIEW";
export const DELETED_COUPON_ALL_VIEW = "DELETED_COUPON_ALL_VIEW";
export const EXPIRED_COUPON_ALL_VIEW = "EXPIRED_COUPON_ALL_VIEW";
export const COUPON_USAGE_HISTORY_ALL_VIEW = "COUPON_USAGE_HISTORY_ALL_VIEW";

// coupon find one
export const PENDING_COUPON_FIND_ONE = "PENDING_COUPON_FIND_ONE";
export const ACTIVE_COUPON_FIND_ONE = "ACTIVE_COUPON_FIND_ONE";
export const REJECTED_COUPON_FIND_ONE = "REJECTED_COUPON_FIND_ONE";
export const DELETED_COUPON_FIND_ONE = "DELETED_COUPON_FIND_ONE";
export const EXPIRED_COUPON_FIND_ONE = "EXPIRED_COUPON_FIND_ONE";
export const COUPON_USAGE_HISTORY_FIND_ONE = "COUPON_USAGE_HISTORY_FIND_ONE";

// edit coupon
export const GENERAL_COUPON_EDIT = "GENERAL_COUPON_EDIT";
export const NEWACCOUNT_COUPON_EDIT = "NEWACCOUNT_COUPON_EDIT";
export const NEWACCOUNT_LIFE_SPAN_COUPON_EDIT =
  "NEWACCOUNT_LIFE_SPAN_COUPON_EDIT";
export const PAYMENT_METHOD_COUPON_EDIT = "PAYMENT_METHOD_COUPON_EDIT";
export const BOOKING_DESTINATION_COUPON_EDIT =
  "BOOKING_DESTINATION_COUPON_EDIT";
export const PICKUP_DROPOFF_COUPON_EDIT = "PICKUP_DROPOFF_COUPON_EDIT";
export const RENTAL_PACKAGE_COUPON_EDIT = "RENTAL_PACKAGE_COUPON_EDIT";
export const BOOKING_DISTANCE_COUPON_EDIT = "BOOKING_DISTANCE_COUPON_EDIT";
export const OUTSTATION_PACKAGE_COUPON_EDIT = "OUTSTATION_PACKAGE_COUPON_EDIT";
export const ACTIVE_COUPON_EDIT = "ACTIVE_COUPON_EDIT";

// approve coupon
export const APPROVE_COUPON = "APPROVE_COUPON";
// reject coupon
export const REJECT_COUPON = "REJECT_COUPON";
// delete coupon
export const DELETE_COUPON = "DELETE_COUPON";

// Referral
export const CREATE_REFERRAL = "CREATE_REFERRAL";

// send review referral
export const SEND_REVIEW_REFERRAL = "SEND_REVIEW_REFERRAL";

// find all referral
export const REVIEW_REQUIRED_REFERRAL_ALL_VIEW =
  "REVIEW_REQUIRED_REFERRAL_ALL_VIEW";
export const ACTIVE_REFERRAL_ALL_VIEW = "ACTIVE_REFERRAL_ALL_VIEW";
export const REJECTED_REFERRAL_ALL_VIEW = "REJECTED_REFERRAL_ALL_VIEW";
export const DELETED_REFERRAL_ALL_VIEW = "DELETED_REFERRAL_ALL_VIEW";
export const EXPIRED_REFERRAL_ALL_VIEW = "EXPIRED_REFERRAL_ALL_VIEW";
export const REF_SENDER_USAGE_HISTORY_FIND_ALL =
  "REF_SENDER_USAGE_HISTORY_FIND_ALL";
export const REF_RECEIVER_USAGE_HISTORY_FIND_ALL =
  "REF_RECEIVER_USAGE_HISTORY_FIND_ALL";

// find one referral
export const REVIEW_REQUIRED_REFRRAL_FIND_ONE =
  "REVIEW_REQUIRED_REFRRAL_FIND_ONE";
export const ACTIVE_REFERRAL_FIND_ONE = "ACTIVE_REFERRAL_FIND_ONE";
export const REJECTED_REFERRAL_FIND_ONE = "REJECTED_REFERRAL_FIND_ONE";
export const DELETED_REFERRAL_FIND_ONE = "DELETED_REFERRAL_FIND_ONE";
export const EXPIRED_REFERRAL_FIND_ONE = "EXPIRED_REFERRAL_FIND_ONE";
export const REF_SENDER_USAGE_HISTORY_FIND_ONE =
  "REF_SENDER_USAGE_HISTORY_FIND_ONE";
export const REF_RECEIVER_USAGE_HISTORY_FIND_ONE =
  "REF_RECEIVER_USAGE_HISTORY_FIND_ONE";

// approve referral
export const APPROVE_REFERRAL = "APPROVE_REFERRAL";

// reject referral
export const REJECT_REFERRAL = "REJECT_REFERRAL";

// delete referral
export const DELETE_REFERRAL = "DELETE_REFERRAL";

// edit referral
export const REVIEW_REQ_REFERRAL_EDIT = "REVIEW_REQ_REFERRAL_EDIT";
export const REVIEW_REQ_REFERRAL_BROADCAST_EDIT =
  "REVIEW_REQ_REFERRAL_BROADCAST_EDIT";
export const ACTIVE_REFERRAL_EDIT = "ACTIVE_REFERRAL_EDIT";
export const ACTIVE_REFERRAL_BROADCAST_EDIT = "ACTIVE_REFERRAL_BROADCAST_EDIT";

export const DROPDOWNLIST_RIDER_ACTIVE_REFERRAL =
  "DROPDOWNLIST_RIDER_ACTIVE_REFERRAL";
export const DROPDOWNLIST_RIDER_PENDING_REFERRAL =
  "DROPDOWNLIST_RIDER_PENDING_REFERRAL";
export const DROPDOWNLIST_RIDER_DELETED_REFERRAL =
  "DROPDOWNLIST_RIDER_DELETED_REFERRAL";
export const DROPDOWNLIST_RIDER_EXPIRED_REFERRAL =
  "DROPDOWNLIST_RIDER_EXPIRED_REFERRAL";
export const DROPDOWNLIST_RIDER_REJECTED_REFERRAL =
  "DROPDOWNLIST_RIDER_REJECTED_REFERRAL";
export const DROPDOWNLIST_RIDER_USAGE_REFERRAL =
  "DROPDOWNLIST_RIDER_USAGE_REFERRAL";

/**********Driver Referral******* */
export const DRIVER_REF_REVIEW_REQ_LIST = "DRIVER_REF_REVIEW_REQ_LIST";
export const DRIVER_REF_ACTIVE_LIST = "DRIVER_REF_ACTIVE_LIST";
export const DRIVER_REF_REJECTED_LIST = "DRIVER_REF_REJECTED_LIST";
export const DRIVER_REF_DELETED_LIST = "DRIVER_REF_DELETED_LIST";
export const DRIVER_REF_EXPIRED_ID_LIST = "DRIVER_REF_EXPIRED_ID_LIST";
export const CREATE_DRIVER_TO_DRIVER_REFERRAL =
  "CREATE_DRIVER_TO_DRIVER_REFERRAL";
export const CREATE_DRIVER_TO_RIDER_REFERRAL =
  "CREATE_DRIVER_TO_RIDER_REFERRAL";
export const DRIVER_ACTIVE_REF_FIND_ONE = "DRIVER_ACTIVE_REF_FIND_ONE";
export const DRIVER_ACTIVE_REF_EDIT = "DRIVER_ACTIVE_REF_EDIT";
export const DRIVER_ACTIVE_REF_BROADCAST_EDIT =
  "DRIVER_ACTIVE_REF_BROADCAST_EDIT";
export const APPROVE_DRIVER_REF = "APPROVE_DRIVER_REF";
export const REVIEW_REQ_DRIVER_REF_FIND_ONE = "REVIEW_REQ_DRIVER_REF_FIND_ONE";
export const REVIEW_REQ_DRIVER_REF_D_TO_D_EDIT =
  "REVIEW_REQ_DRIVER_REF_D_TO_D_EDIT";
export const REVIEW_REQ_DRIVER_REF_D_TO_R_EDIT =
  "REVIEW_REQ_DRIVER_REF_D_TO_R_EDIT";
export const REVIEW_REQ_DRIVER_REF_BROADCAST_EDIT =
  "REVIEW_REQ_DRIVER_REF_BROADCAST_EDIT";
export const SEND_REVIEW_DRIVER_REFERRAL = "SEND_REVIEW_DRIVER_REFERRAL";
export const DRVIER_REF_SENDER_USAGE_HISTORY_LIST =
  "DRVIER_REF_SENDER_USAGE_HISTORY_LIST";
export const DRVIER_REF_RECEIVER_USAGE_HISTORY_LIST =
  "DRVIER_REF_RECEIVER_USAGE_HISTORY_LIST";
export const DRIVER_REF_SENDER_USAGE_HISTORY =
  "DRIVER_REF_SENDER_USAGE_HISTORY";
export const DRIVER_REF_RECEIVER_USAGE_HISTORY =
  "DRIVER_REF_RECEIVER_USAGE_HISTORY";
export const DELETE_DRIVER_REF = "DELETE_DRIVER_REF";
export const DELETE_DRIVER_REF_FIND_ONE = "DELETE_DRIVER_REF_FIND_ONE";
export const REJECT_DRIVER_REF = "REJECT_DRIVER_REF";
export const REJECT_DRIVER_REF_FIND_ONE = "REJECT_DRIVER_REF_FIND_ONE";
export const EXPIRED_DRIVER_REF_ID = "EXPIRED_DRIVER_REF_ID";
export const CLEAR_RIDER_REFERRAL = "CLEAR_RIDER_REFERRAL";
export const CLEAR_DRIVER_REFERRAL = "CLEAR_DRIVER_REFERRAL";

export const DROPDOWNLIST_DRIVER_ACTIVE_REFERRAL =
  "DROPDOWNLIST_DRIVER_ACTIVE_REFERRAL";
export const DROPDOWNLIST_DRIVER_PENDING_REFERRAL =
  "DROPDOWNLIST_DRIVER_PENDING_REFERRAL";
export const DROPDOWNLIST_DRIVER_DELETED_REFERRAL =
  "DROPDOWNLIST_DRIVER_DELETED_REFERRAL";
export const DROPDOWNLIST_DRIVER_EXPIRED_REFERRAL =
  "DROPDOWNLIST_DRIVER_EXPIRED_REFERRAL";
export const DROPDOWNLIST_DRIVER_REJECTED_REFERRAL =
  "DROPDOWNLIST_DRIVER_REJECTED_REFERRAL";
export const DROPDOWNLIST_DRIVER_USAGE_REFERRAL =
  "DROPDOWNLIST_DRIVER_USAGE_REFERRAL";
export const REFERRAL_RIDETYPE_LIST = "REFERRAL_RIDETYPE_LIST";

/********Complaints *********/

export const RIDER_PENDING_COMPLAINTS_LIST = "RIDER_PENDING_COMPLAINTS_LIST";
export const DRIVER_PENDING_COMPLAINTS_LIST = "DRIVER_PENDING_COMPLAINTS_LIST";
export const RIDER_INPROGRESS_COMPLAINTS_LIST =
  "RIDER_INPROGRESS_COMPLAINTS_LIST";
export const DRIVER_INPROGRESS_COMPLAINTS_LIST =
  "DRIVER_INPROGRESS_COMPLAINTS_LIST";
export const RIDER_RESOLVED_CLOSED_COMPLAINTS_LIST =
  "RIDER_RESOLVED_CLOSED_COMPLAINTS_LIST";
export const DRIVER_RESOLVED_CLOSED_COMPLAINTS_LIST =
  "DRIVER_RESOLVED_CLOSED_COMPLAINTS_LIST";
export const RIDER_PENDING_COMPLAINT = "RIDER_PENDING_COMPLAINT";
export const RIDER_INPROGRESS_COMPLAINT = "RIDER_INPROGRESS_COMPLAINT";
export const DRIVER_PENDING_COMPLAINT = "DRIVER_PENDING_COMPLAINT";
export const DRIVER_INPROGRESS_COMPLAINT = "DRIVER_INPROGRESS_COMPLAINT";
export const DRIVER_COMPLAINT_INITIATE = "DRIVER_COMPLAINT_INITIATE";
export const RIDER_COMPLAINT_INITIATE = "RIDER_COMPLAINT_INITIATE";
export const DRIVER_COMPLAINT_ASSIGN = "DRIVER_COMPLAINT_ASSIGN";
export const RIDER_COMPLAINT_ASSIGN = "RIDER_COMPLAINT_ASSIGN";
export const ASSIGN_TO_ADMIN_LIST = "ASSIGN_TO_ADMIN_LIST";
export const DRIVER_INPROG_COMPLAINT_REASSIGN =
  "DRIVER_INPROG_COMPLAINT_REASSIGN";
export const RIDER_INPROG_COMPLAINT_REASSIGN =
  "RIDER_INPROG_COMPLAINT_REASSIGN";
export const RIDER_RES_COLSED_COMPLAINT = "RIDER_RES_COLSED_COMPLAINT";
export const DRIVER_RES_COLSED_COMPLAINT = "DRIVER_RES_COLSED_COMPLAINT";
export const BOOKING_ID_LIST = "BOOKING_ID_LIST";
export const GENERATE_COMP_RIDER = "GENERATE_COMP_RIDER";
export const GENERATE_COMP_DRIVER = "GENERATE_COMP_DRIVER";
export const CALL_COMPLAINT_DESCRIPTION = "CALL_COMPLAINT_DESCRIPTION";
export const RIDER_COMPL_PENDING_DROPDOWN = "RIDER_COMPL_PENDING_DROPDOWN";
export const DRIVER_COMPL_PENDING_DROPDOWN = "DRIVER_COMPL_PENDING_DROPDOWN";
export const RIDER_COMPL_INPROGRESS_DROPDOWN =
  "RIDER_COMPL_INPROGRESS_DROPDOWN";
export const DRIVER_COMPL_INPROGRESS_DROPDOWN =
  "DRIVER_COMPL_INPROGRESS_DROPDOWN";
export const RIDER_COMPL_RESLOVED_DROPDOWN = "RIDER_COMPL_RESLOVED_DROPDOWN";
export const DRIVER_COMPL_RESLOVED_DROPDOWN = "DRIVER_COMPL_RESLOVED_DROPDOWN";

/****** SOS ********/
export const SOS_LOCAL_RESPONDER_LIST = "SOS_LOCAL_RESPONDER_LIST";
export const SOS_LOCAL_RESPONDER = "SOS_LOCAL_RESPONDER";
export const ADD_SOS_LOCAL_RESPNDER = "ADD_SOS_LOCAL_RESPNDER";
export const UPDATE_SOS_LOCAL_RESPONDER = "UPDATE_SOS_LOCAL_RESPONDER";
export const DELETE_SOS_LOCAL_RESPONDER = "DELETE_SOS_LOCAL_RESPONDER";
export const DRIVER_SOS_ASSIGN = "DRIVER_SOS_ASSIGN";
export const DRIVER_SOS_INITIATE = "DRIVER_SOS_INITIATE";
export const DRIVER_PENDING_SOS = "DRIVER_PENDING_SOS";
export const DRIVER_PENDING_SOS_LIST = "DRIVER_PENDING_SOS_LIST";
export const RIDER_SOS_ASSIGN = "RIDER_SOS_ASSIGN";
export const RIDER_SOS_INITIATE = "RIDER_SOS_INITIATE";
export const RIDER_PENDING_SOS = "RIDER_PENDING_SOS";
export const RIDER_PENDING_SOS_LIST = "RIDER_PENDING_SOS_LIST";
export const RIDER_ID_LIST = "RIDER_ID_LIST";
export const DRIVER_ID_LIST = "DRIVER_ID_LIST";

export const DRIVER_INPROGRESS_SOS = "DRIVER_INPROGRESS_SOS";
export const DRIVER_INPROGRESS_SOS_LIST = "DRIVER_INPROGRESS_SOS_LIST";
export const DRIVER_INPROG_SOS_REASSIGN = "DRIVER_INPROG_SOS_REASSIGN";
export const RIDER_INPROGRESS_SOS = "RIDER_INPROGRESS_SOS";
export const RIDER_INPROGRESS_SOS_LIST = "RIDER_INPROGRESS_SOS_LIST";
export const RIDER_INPROG_SOS_REASSIGN = "RIDER_INPROG_SOS_REASSIGN";

export const TRACKING_LIST = "TRACKING_LIST";

export const DRIVER_RESOLVED_CLOSED_SOS_LIST =
  "DRIVER_RESOLVED_CLOSED_SOS_LIST";
export const DRIVER_RES_COLSED_SOS = "DRIVER_RES_COLSED_SOS";
export const RIDER_RESOLVED_CLOSED_SOS_LIST = "RIDER_RESOLVED_CLOSED_SOS_LIST";
export const RIDER_RES_COLSED_SOS = "RIDER_RES_COLSED_SOS";
export const RIDER_SOS_PENDING_DROPDOWN = "RIDER_SOS_PENDING_DROPDOWN";
export const DRIVER_SOS_PENDING_DROPDOWN = "DRIVER_SOS_PENDING_DROPDOWN";
export const RIDER_SOS_INPROGRESS_DROPDOWN = "RIDER_SOS_INPROGRESS_DROPDOWN";
export const DRIVER_SOS_INPROGRESS_DROPDOWN = "DRIVER_SOS_INPROGRESS_DROPDOWN";

export const DRIVER_CLOSE_SOS = "DRIVER_CLOSE_SOS";
export const DRIVER_FORWARD_SOS = "DRIVER_FORWARD_SOS";
export const DRIVER_RESOLVE_SOS = "DRIVER_RESOLVE_SOS";
export const MY_SOS_DRIVER_LIST = "MY_SOS_DRIVER_LIST";
export const MY_SOS_RIDER_LIST = "MY_SOS_RIDER_LIST";
export const RIDER_CLOSE_SOS = "RIDER_CLOSE_SOS";
export const RIDER_FORWARD_SOS = "RIDER_FORWARD_SOS";
export const RIDER_RESOLVE_SOS = "RIDER_RESOLVE_SOS";
export const LOCAL_RESPONDER_CONATACT_LIST = "LOCAL_RESPONDER_CONATACT_LIST";

// call
export const GENERATE_SOS_CALL_RIDER = "GENERATE_SOS_CALL_RIDER";
export const GENERATE_SOS_CALL_DRIVER = "GENERATE_SOS_CALL_DRIVER";
export const ASSIGN_SOS_TO_ADMIN_LIST = "ASSIGN_SOS_TO_ADMIN_LIST";

//My Complaints

export const MY_COMPLAINTS_LIST = "MY_COMPLAINTS_LIST";
export const MY_COMPLAINTS_RIDER_LIST = "MY_COMPLAINTS_RIDER_LIST";
export const DRIVER_RESOLVE_COMPLAINT = "DRIVER_RESOLVE_COMPLAINT";
export const DRIVER_CLOSE_COMPLAINT = "DRIVER_CLOSE_COMPLAINT";
export const DRIVER_FORWARD_COMPLAINT = "DRIVER_FORWARD_COMPLAINT";
export const RIDER_RESOLVE_COMPLAINT = "RIDER_RESOLVE_COMPLAINT";
export const RIDER_CLOSE_COMPLAINT = "RIDER_CLOSE_COMPLAINT";
export const RIDER_FORWARD_COMPLAINT = "RIDER_FORWARD_COMPLAINT";

// incentives
export const CREATE_DRIVER_INCENTIVE = "CREATE_DRIVER_INCENTIVE";
export const DRIVER_INCENTIVE_PEND_LIST = "DRIVER_INCENTIVE_PEND_LIST";
export const DRIVER_INCENTIVE_PENDING = "DRIVER_INCENTIVE_PENDING";
export const DRIVER_INCENTIVE_PENDING_EDIT = "DRIVER_INCENTIVE_PENDING_EDIT";

export const DRIVER_INCENTIVE_ACTIVE_LIST = "DRIVER_INCENTIVE_ACTIVE_LIST";
export const DRIVER_INCENTIVE_ACTIVE = "DRIVER_INCENTIVE_ACTIVE";
export const DRIVER_INCENTIVE_ACTIVE_EDIT = "DRIVER_INCENTIVE_ACTIVE_EDIT";
export const DRIVER_INCENTIVE_ACTIVE_CAMPAIGN_EDIT =
  "DRIVER_INCENTIVE_ACTIVE_CAMPAIGN_EDIT";
export const APPROVE_DRIVER_INCENTIVE = "APPROVE_DRIVER_INCENTIVE";

export const DRIVER_INCENTIVE_REJECTED_LIST = "DRIVER_INCENTIVE_REJECTED_LIST";
export const DRIVER_INCENTIVE_REJECTED = "DRIVER_INCENTIVE_REJECTED";
export const REJECT_DRIVER_INCENTIVE = "REJECT_DRIVER_INCENTIVE";

export const DRIVER_INCENTIVE_DELETED_LIST = "DRIVER_INCENTIVE_DELETED_LIST";
export const DRIVER_INCENTIVE_DELETED = "DRIVER_INCENTIVE_DELETED";
export const DELETE_DRIVER_INCENTIVE = "DELETE_DRIVER_INCENTIVE";

export const DRIVER_INCENTIVE_EXPIRED_LIST = "DRIVER_INCENTIVE_EXPIRED_LIST";
export const DRIVER_INCENTIVE_EXPIRED = "DRIVER_INCENTIVE_EXPIRED";

export const DRIVER_INCENTIVE_USAGE_HIS_LIST =
  "DRIVER_INCENTIVE_USAGE_HIS_LIST";
export const DRIVER_INCENTIVE_USAGE_HIS = "DRIVER_INCENTIVE_USAGE_HIS";

export const INCENTIVE_MAIN_ZONE_LIST = "INCENTIVE_MAIN_ZONE_LIST";
export const INCENTIVE_RIDE_TYPE_LIST = "INCENTIVE_RIDE_TYPE_LIST";

export const DRI_INCENTIVE_EXPIRE_DRP_DWN = "DRI_INCENTIVE_EXPIRE_DRP_DWN";
export const DRI_INCENTIVE_REJECT_DRP_DWN = "DRI_INCENTIVE_REJECT_DRP_DWN";
export const DRI_INCENTIVE_DELETE_DRP_DWN = "DRI_INCENTIVE_DELETE_DRP_DWN";
export const DRI_INCENTIVE_REVREQ_DRP_DWN = "DRI_INCENTIVE_REVREQ_DRP_DWN";
export const DRI_INCENTIVE_ACTIVE_DRP_DWN = "DRI_INCENTIVE_ACTIVE_DRP_DWN";
export const DRI_INCENTIVE_USGHIS_DRP_DWN = "DRI_INCENTIVE_USGHIS_DRP_DWN";

/*******BroadCast********/

export const RIDER_BROADCAST_PEND_LIST = "RIDER_BROADCAST_PEND_LIST";

export const RIDER_BROADCAST_ACTIVE_LIST = "RIDER_BROADCAST_ACTIVE_LIST";
export const RIDER_BROADCAST_ACTIVE_FIND_ONE =
  "RIDER_BROADCAST_ACTIVE_FIND_ONE";
export const RIDER_BROADCAST_ACTIVE_EDIT = "RIDER_BROADCAST_ACTIVE_EDIT";
export const RIDER_BROADCAST_APPROVE = "RIDER_BROADCAST_APPROVE";
export const RIDER_BROADCAST_REJECT = "RIDER_BROADCAST_REJECT";

export const RIDER_BROADCAST_REJECT_LIST = "RIDER_BROADCAST_REJECT_LIST";
export const RIDER_BROADCAST_REJECT_FIND_ONE =
  "RIDER_BROADCAST_REJECT_FIND_ONE";

export const RIDER_BROADCAST_DELETED_LIST = "RIDER_BROADCAST_DELETED_LIST";
export const RIDER_BROADCAST_DELETE_FIND_ONE =
  "RIDER_BROADCAST_DELETE_FIND_ONE";
export const RIDER_BROADCAST_EXPIRED_LIST = "RIDER_BROADCAST_EXPIRED_LIST";
export const RIDER_BROADCAST_EXPIRED_FIND_ONE =
  "RIDER_BROADCAST_EXPIRED_FIND_ONE";
export const CREATE_RIDER_BROADCAST = "CREATE_RIDER_BROADCAST";
export const REV_REQ_RIDER_BROADCAST = "REV_REQ_RIDER_BROADCAST";
export const EDIT_REV_REQ_RIDER_BROADCAST = "EDIT_REV_REQ_RIDER_BROADCAST";

export const DELETE_RIDER_BROADCAST = "DELETE_RIDER_BROADCAST";

export const REV_REQ_RIDER_BROADCAST_DRP_DWN =
  "REV_REQ_RIDER_BROADCAST_DRP_DWN";
export const RIDER_BROADCAST_ACTIVE_DRP_DWN = "RIDER_BROADCAST_ACTIVE_DRP_DWN";
export const RIDER_BROADCAST_REJECT_DRP_DWN = "RIDER_BROADCAST_REJECT_DRP_DWN";
export const RIDER_BROADCAST_DELETE_DRP_DWN = "RIDER_BROADCAST_DELETE_DRP_DWN";
export const RIDER_BROADCAST_EXPIRED_DRP_DWN =
  "RIDER_BROADCAST_EXPIRED_DRP_DWN";

export const DRIVER_BROADCAST_PEND_LIST = "DRIVER_BROADCAST_PEND_LIST";
export const DRIVER_BROADCAST_ACTIVE_LIST = "DRIVER_BROADCAST_ACTIVE_LIST";
export const DRIVER_BROADCAST_REJECT_LIST = "DRIVER_BROADCAST_REJECT_LIST";
export const DRIVER_BROADCAST_DELETED_LIST = "DRIVER_BROADCAST_DELETED_LIST";
export const DRIVER_BROADCAST_EXPIRED_LIST = "DRIVER_BROADCAST_EXPIRED_LIST";

export const DRIVER_BROADCAST_REV_REQ_DRP_DWN =
  "DRIVER_BROADCAST_REV_REQ_DRP_DWN";
export const DRIVER_BROADCAST_ACTIVE_DRP_DWN =
  "DRIVER_BROADCAST_ACTIVE_DRP_DWN";
export const DRIVER_BROADCAST_REJECT_DRP_DWN =
  "DRIVER_BROADCAST_REJECT_DRP_DWN";
export const DRIVER_BROADCAST_DELETE_DRP_DWN =
  "DRIVER_BROADCAST_DELETE_DRP_DWN";
export const DRIVER_BROADCAST_EXPIRE_DRP_DWN =
  "DRIVER_BROADCAST_EXPIRE_DRP_DWN";

export const DRIVER_BROADCAST_ACTIVE_FIND_ONE =
  "DRIVER_BROADCAST_ACTIVE_FIND_ONE";
export const REV_REQ_DRIVER_BROADCAST = "REV_REQ_DRIVER_BROADCAST";
export const DRIVER_BROADCAST_DELETE_FIND_ONE =
  "DRIVER_BROADCAST_DELETE_FIND_ONE";
export const DRIVER_BROADCAST_REJECT_FIND_ONE =
  "DRIVER_BROADCAST_REJECT_FIND_ONE";
export const DRIVER_BROADCAST_EXPIRED_FIND_ONE =
  "DRIVER_BROADCAST_EXPIRED_FIND_ONE";

export const CREATE_DRIVER_BROADCAST = "CREATE_DRIVER_BROADCAST";
export const EDIT_REV_REQ_DRIVER_BROADCAST = "EDIT_REV_REQ_DRIVER_BROADCAST";
export const DELETE_DRIVER_BROADCAST = "DELETE_DRIVER_BROADCAST";
export const DRIVER_BROADCAST_ACTIVE_EDIT = "DRIVER_BROADCAST_ACTIVE_EDIT";
export const DRIVER_BROADCAST_APPROVE = "DRIVER_BROADCAST_APPROVE";
export const DRIVER_BROADCAST_REJECT = "DRIVER_BROADCAST_REJECT";
export const RIDETYPE_BROADCAST_DROPDOWN = "RIDETYPE_BROADCAST_DROPDOWN";
// chat Section
export const STORAGED_MESSAGE = "STORAGED_MESSAGE";
export const STORAGED_SOS_MESSAGE = "STORAGED_SOS_MESSAGE";
export const ALL_COMPLAINTS_MESSAGES = "ALL_COMPLAINTS_MESSAGES";
export const ALL_SOS_MESSAGES = "ALL_SOS_MESSAGES";
export const COMPLAINT_MESSAGE_READ = "COMPLAINT_MESSAGE_READ";
export const SOS_MESSAGE_READ = "SOS_MESSAGE_READ";
export const CHAT_IMAGE_UPLOAD = "CHAT_IMAGE_UPLOAD";
export const CHAT_LIST_LOAD = "CHAT_LIST_LOAD";
export const CHAT_LIST_LOAD_MORE = "CHAT_LIST_LOAD_MORE";
export const CHAT_LIST_LATEST = "CHAT_LIST_LATEST";
export const SEND_SOS_MESSAGE = "SEND_SOS_MESSAGE";
export const DRIVER_SEND_SOS_MESSAGE = "DRIVER_SEND_SOS_MESSAGE";
export const DRIVER_SEND_COMPLAINT_MESSAGE = "DRIVER_SEND_COMPLAINT_MESSAGE";
export const RIDER_SEND_COMPLAINT_MESSAGE = "RIDER_SEND_COMPLAINT_MESSAGE";

export const CREATE_INCENTIVE_DATA = "CREATE_INCENTIVE_DATA";
// Faq Section

export const RIDER_FAQ_HELP_COVID_FIND_ALL = "RIDER_FAQ_HELP_COVID_FIND_ALL";
export const RIDER_FAQ_HELP_PROFILE_ACCOUNT_FIND_ALL =
  "RIDER_FAQ_HELP_PROFILE_ACCOUNT_FIND_ALL";
export const RIDER_FAQ_HELP_MY_TRIPS_FIND_ALL =
  "RIDER_FAQ_HELP_MY_TRIPS_FIND_ALL";
export const RIDER_FAQ_HELP_PAYMENT_FIND_ALL =
  "RIDER_FAQ_HELP_PAYMENT_FIND_ALL";
export const RIDER_FAQ_HELP_SAFETY_FIND_ALL = "RIDER_FAQ_HELP_SAFETY_FIND_ALL";
export const RIDER_FAQ_HELP_TROUBLESHOOT_FIND_ALL =
  "RIDER_FAQ_HELP_TROUBLESHOOT_FIND_ALL";
export const RIDER_FAQ_HELP_GUIDE_TO_COMRIDE_FIND_ALL =
  "RIDER_FAQ_HELP_GUIDE_TO_COMRIDE_FIND_ALL";
export const RIDER_FAQ_HELP_REFERAL_FIND_ALL =
  "RIDER_FAQ_HELP_REFERAL_FIND_ALL";

export const RIDER_FAQ_DURING_TRIP_LOCAL_FIND_ALL =
  "RIDER_FAQ_DURING_TRIP_LOCAL_FIND_ALL";
export const RIDER_FAQ_DURING_TRIP_RENTAL_FIND_ALL =
  "RIDER_FAQ_DURING_TRIP_RENTAL_FIND_ALL";
export const RIDER_FAQ_DURING_TRIP_ONEWAY_FIND_ALL =
  "RIDER_FAQ_DURING_TRIP_ONEWAY_FIND_ALL";
export const RIDER_FAQ_DURING_TRIP_ROUND_FIND_ALL =
  "RIDER_FAQ_DURING_TRIP_ROUND_FIND_ALL";

export const RIDER_FAQ_AFTER_TRIP_LOCAL_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_LOCAL_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_RENTAL_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_RENTAL_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_ONEWAY_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_ONEWAY_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_ROUND_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_ROUND_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_PAYMENT_LOCAL_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_PAYMENT_LOCAL_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_PAY_RENT_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_PAY_RENT_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_PAY_ONEWAY_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_PAY_ONEWAY_FIND_ALL";
export const RIDER_FAQ_AFTER_TRIP_PAY_ROUND_FIND_ALL =
  "RIDER_FAQ_AFTER_TRIP_PAY_ROUND_FIND_ALL";

export const DRIVER_FAQ_HELP_COVID_FIND_ALL = "DRIVER_FAQ_HELP_COVID_FIND_ALL";
export const DRIVER_FAQ_HELP_MY_ACCOUNT_FIND_ALL =
  "DRIVER_FAQ_HELP_MY_ACCOUNT_FIND_ALL";
export const DRIVER_FAQ_HELP_CANCELLATION_POLICY_FIND_ALL =
  "DRIVER_FAQ_HELP_CANCELLATION_POLICY_FIND_ALL";
export const DRIVER_FAQ_HELP_PAYMENT_FIND_ALL =
  "DRIVER_FAQ_HELP_PAYMENT_FIND_ALL";
export const DRIVER_FAQ_HELP_SAFETY_FIND_ALL =
  "DRIVER_FAQ_HELP_SAFETY_FIND_ALL";
export const DRIVER_FAQ_COMRIDE_SERVICE_FIND_ALL =
  "DRIVER_FAQ_COMRIDE_SERVICE_FIND_ALL";
export const DRIVER_FAQ_HELP_GUIDE_TO_COMRIDE_FIND_ALL =
  "DRIVER_FAQ_HELP_GUIDE_TO_COMRIDE_FIND_ALL";
export const DRIVER_FAQ_HELP_REFERAL_FIND_ALL =
  "DRIVER_FAQ_HELP_REFERAL_FIND_ALL";

export const DRIVER_FAQ_DURING_TRIP_LOCAL_FIND_ALL =
  "DRIVER_FAQ_DURING_TRIP_LOCAL_FIND_ALL";
export const DRIVER_FAQ_DURING_TRIP_RENTAL_FIND_ALL =
  "DRIVER_FAQ_DURING_TRIP_RENTAL_FIND_ALL";
export const DRIVER_FAQ_DURING_TRIP_ONEWAY_FIND_ALL =
  "DRIVER_FAQ_DURING_TRIP_ONEWAY_FIND_ALL";
export const DRIVER_FAQ_DURING_TRIP_ROUND_FIND_ALL =
  "DRIVER_FAQ_DURING_TRIP_ROUND_FIND_ALL";
export const CREATE_FAQ_OR_TOPIC = "CREATE_FAQ_OR_TOPIC";
export const VIEW_FAQ_OR_TOPIC = "VIEW_FAQ_OR_TOPIC";
export const EDIT_FAQ_OR_TOPIC = "EDIT_FAQ_OR_TOPIC";
export const DELETE_FAQ_OR_TOPIC = "DELETE_FAQ_OR_TOPIC";
export const CREATE_TOPIC_UNDER_FAQ = "CREATE_TOPIC_UNDER_FAQ";
export const EDIT_TOPIC_UNDER_FAQ = "EDIT_TOPIC_UNDER_FAQ";
export const VIEW_TOPIC_UNDER_FAQ = "VIEW_TOPIC_UNDER_FAQ";
export const DELETE_TOPIC_UNDER_FAQ = "DELETE_TOPIC_UNDER_FAQ";
export const TOPIC_UNDER_FAQ_RIDER_LIST = "TOPIC_UNDER_FAQ_RIDER_LIST";
export const TOPIC_UNDER_FAQ_DRIVER_LIST = "TOPIC_UNDER_FAQ_DRIVER_LIST";
export const ACTIVE_FAQ_OR_TOPIC = "ACTIVE_FAQ_OR_TOPIC";
export const INACTIVE_FAQ_OR_TOPIC = "INACTIVE_FAQ_OR_TOPIC";

export const NSE_R_NEWACCOUNT_LIST = "NSE_R_NEWACCOUNT_LIST";
export const NSE_R_GENERAL_ACC_LIST = "NSE_R_GENERAL_ACC_LIST";
export const NSE_R_POLICY_UPDATE_LIST = "NSE_R_POLICY_UPDATE_LIST";
export const NSE_R_SECURITY_LIST = "NSE_R_SECURITY_LIST";

export const NSE_R_BOOKINGLOCAL_NO_RIDES_LIST =
  "NSE_R_BOOKINGLOCAL_NO_RIDES_LIST";
export const NSE_R_BOOKINGLOCAL_ONGOING_LIST =
  "NSE_R_BOOKINGLOCAL_ONGOING_LIST";
export const NSE_R_BOOKINGLOCAL_CANCELLED_LIST =
  "NSE_R_BOOKINGLOCAL_CANCELLED_LIST";
export const NSE_R_BOOKINGLOCAL_ACCIDENT_LIST =
  "NSE_R_BOOKINGLOCAL_ACCIDENT_LIST";
export const NSE_R_BOOKINGLOCAL_REVIEW_LIST = "NSE_R_BOOKINGLOCAL_REVIEW_LIST";

export const NSE_R_BOOKINGRENTAL_NO_RIDES_LIST =
  "NSE_R_BOOKINGRENTAL_NO_RIDES_LIST";
export const NSE_R_BOOKINGRENTAL_ONGOING_LIST =
  "NSE_R_BOOKINGRENTAL_ONGOING_LIST";
export const NSE_R_BOOKINGRENTAL_CANCELLED_LIST =
  "NSE_R_BOOKINGRENTAL_CANCELLED_LIST";
export const NSE_R_BOOKINGRENTAL_ACCIDENT_LIST =
  "NSE_R_BOOKINGRENTAL_ACCIDENT_LIST";
export const NSE_R_BOOKINGRENTAL_REVIEW_LIST =
  "NSE_R_BOOKINGRENTAL_REVIEW_LIST";

export const NSE_R_BOOKINGONEWAY_NO_RIDES_LIST =
  "NSE_R_BOOKINGONEWAY_NO_RIDES_LIST";
export const NSE_R_BOOKINGONEWAY_ONGOING_LIST =
  "NSE_R_BOOKINGONEWAY_ONGOING_LIST";
export const NSE_R_BOOKINGONEWAY_CANCELLED_LIST =
  "NSE_R_BOOKINGONEWAY_CANCELLED_LIST";
export const NSE_R_BOOKINGONEWAY_ACCIDENT_LIST =
  "NSE_R_BOOKINGONEWAY_ACCIDENT_LIST";
export const NSE_R_BOOKINGONEWAY_REVIEW_LIST =
  "NSE_R_BOOKINGONEWAY_REVIEW_LIST";
export const NSE_R_BOOKINGONEWAY_RIDESCHEDULED_LIST =
  "NSE_R_BOOKINGONEWAY_RIDESCHEDULED_LIST";
export const NSE_R_BOOKINGONEWAY_ODOMETER_LIST =
  "NSE_R_BOOKINGONEWAY_ODOMETER_LIST";

export const NSE_R_BOOKINGROUND_NO_RIDES_LIST =
  "NSE_R_BOOKINGROUND_NO_RIDES_LIST";
export const NSE_R_BOOKINGROUND_ONGOING_LIST =
  "NSE_R_BOOKINGROUND_ONGOING_LIST";
export const NSE_R_BOOKINGROUND_CANCELLED_LIST =
  "NSE_R_BOOKINGROUND_CANCELLED_LIST";
export const NSE_R_BOOKINGROUND_ACCIDENT_LIST =
  "NSE_R_BOOKINGROUND_ACCIDENT_LIST";
export const NSE_R_BOOKINGROUND_REVIEW_LIST = "NSE_R_BOOKINGROUND_REVIEW_LIST";
export const NSE_R_BOOKINGROUND_RIDESCHEDULED_LIST =
  "NSE_R_BOOKINGROUND_RIDESCHEDULED_LIST";
export const NSE_R_BOOKINGROUND_ODOMETER_LIST =
  "NSE_R_BOOKINGROUND_ODOMETER_LIST";

export const NSE_R_PAYMENT_PENDING_LIST = "NSE_R_PAYMENT_PENDING_LIST";
export const NSE_R_PAYMENT_SUCCESS_LIST = "NSE_R_PAYMENT_SUCCESS_LIST";
export const NSE_R_PAYMENT_RIDER_CURRENTBALANCE_LIST =
  "NSE_R_PAYMENT_RIDER_CURRENTBALANCE_LIST";
export const NSE_R_PAYMENT_WALLET_LIST = "NSE_R_PAYMENT_WALLET_LIST";

export const NSE_R_EMERSOS_DURINGTRIP_LIST = "NSE_R_EMERSOS_DURINGTRIP_LIST";
export const NSE_R_EMERSOS_NOTRIP_LIST = "NSE_R_EMERSOS_NOTRIP_LIST";
export const NSE_R_EMERSOS_MESSAGING_LIST = "NSE_R_EMERSOS_MESSAGING_LIST";

export const NSE_R_IN_APP_MESS_PENDING_LIST = "NSE_R_IN_APP_MESS_PENDING_LIST";
export const NSE_R_IN_APP_MESS_COMPLAINT_LIST =
  "NSE_R_IN_APP_MESS_COMPLAINT_LIST";
export const NSE_R_IN_APP_MESS_RESCLOSED_LIST =
  "NSE_R_IN_APP_MESS_RESCLOSED_LIST";

export const NSE_R_FINDONE = "NSE_R_FINDONE";
export const NSE_R_EDIT = "NSE_R_EDIT";

export const NSE_D_NEWACCOUNT_LIST = "NSE_D_NEWACCOUNT_LIST";
export const NSE_D_NEW_DRIVER_APPL_LIST = "NSE_D_NEW_DRIVER_APPL_LIST";
export const NSE_D_EXIS_DRIVER_APPL_LIST = "NSE_D_EXIS_DRIVER_APPL_LIST";
export const NSE_D_GENERAL_ACC_LIST = "NSE_D_GENERAL_ACC_LIST";
export const NSE_D_ACCOUNT_ACTIVITY_LIST = "NSE_D_ACCOUNT_ACTIVITY_LIST";
export const NSE_D_POLICY_UPDATE_LIST = "NSE_D_POLICY_UPDATE_LIST";
export const NSE_D_DRIVER_PERFORMANCE_LIST = "NSE_D_DRIVER_PERFORMANCE_LIST";
export const NSE_D_SECURITY_LIST = "NSE_D_SECURITY_LIST";

export const NSE_D_BOOKINGLOCAL_ONGOING_LIST =
  "NSE_D_BOOKINGLOCAL_ONGOING_LIST";
export const NSE_D_BOOKINGLOCAL_STOPADDED_LIST =
  "NSE_D_BOOKINGLOCAL_STOPADDED_LIST";
export const NSE_D_BOOKINGLOCAL_DROPOFFUPDATED_LIST =
  "NSE_D_BOOKINGLOCAL_DROPOFFUPDATED_LIST";
export const NSE_D_BOOKINGLOCAL_PAYMENT_LIST =
  "NSE_D_BOOKINGLOCAL_PAYMENT_LIST";
export const NSE_D_BOOKINGLOCAL_CANCELLED_LIST =
  "NSE_D_BOOKINGLOCAL_CANCELLED_LIST";
export const NSE_D_BOOKINGLOCAL_ACCIDENT_LIST =
  "NSE_D_BOOKINGLOCAL_ACCIDENT_LIST";
export const NSE_D_BOOKINGLOCAL_REVIEW_LIST = "NSE_D_BOOKINGLOCAL_REVIEW_LIST";

export const NSE_D_BOOKINGRENTAL_ONGOING_LIST =
  "NSE_D_BOOKINGRENTAL_ONGOING_LIST";
export const NSE_D_BOOKINGRENTAL_DAILYLIMIT_REACHED_LIST =
  "NSE_D_BOOKINGRENTAL_DAILYLIMIT_REACHED_LIST";
export const NSE_D_BOOKINGRENTAL_DROPOFFUPDATED_LIST =
  "NSE_D_BOOKINGRENTAL_DROPOFFUPDATED_LIST";
export const NSE_D_BOOKINGRENTAL_PAYMENT_LIST =
  "NSE_D_BOOKINGRENTAL_PAYMENT_LIST";
export const NSE_D_BOOKINGRENTAL_CANCELLED_LIST =
  "NSE_D_BOOKINGRENTAL_CANCELLED_LIST";
export const NSE_D_BOOKINGRENTAL_ACCIDENT_LIST =
  "NSE_D_BOOKINGRENTAL_ACCIDENT_LIST";
export const NSE_D_BOOKINGRENTAL_REVIEW_LIST =
  "NSE_D_BOOKINGRENTAL_REVIEW_LIST";

export const NSE_D_BOOKINGONEWAY_ONGOING_LIST =
  "NSE_D_BOOKINGONEWAY_ONGOING_LIST";
export const NSE_D_BOOKINGONEWAY_ODOMETER_LIST =
  "NSE_D_BOOKINGONEWAY_ODOMETER_LIST";
export const NSE_D_BOOKINGONEWAY_DROPOFFUPDATED_LIST =
  "NSE_D_BOOKINGONEWAY_DROPOFFUPDATED_LIST";
export const NSE_D_BOOKINGONEWAY_PAYMENT_LIST =
  "NSE_D_BOOKINGONEWAY_PAYMENT_LIST";
export const NSE_D_BOOKINGONEWAY_CANCELLED_LIST =
  "NSE_D_BOOKINGONEWAY_CANCELLED_LIST";
export const NSE_D_BOOKINGONEWAY_ACCIDENT_LIST =
  "NSE_D_BOOKINGONEWAY_ACCIDENT_LIST";
export const NSE_D_BOOKINGONEWAY_REVIEW_LIST =
  "NSE_D_BOOKINGONEWAY_REVIEW_LIST";
export const NSE_D_BOOKINGONEWAY_MAXLIMITREACHED_LIST =
  "NSE_D_BOOKINGONEWAY_MAXLIMITREACHED_LIST";

export const NSE_D_BOOKINGROUND_ONGOING_LIST =
  "NSE_D_BOOKINGROUND_ONGOING_LIST";
export const NSE_D_BOOKINGROUND_ODOMETER_LIST =
  "NSE_D_BOOKINGROUND_ODOMETER_LIST";
export const NSE_D_BOOKINGROUND_DROPOFFUPDATED_LIST =
  "NSE_D_BOOKINGROUND_DROPOFFUPDATED_LIST";
export const NSE_D_BOOKINGROUND_PAYMENT_LIST =
  "NSE_D_BOOKINGROUND_PAYMENT_LIST";
export const NSE_D_BOOKINGROUND_CANCELLED_LIST =
  "NSE_D_BOOKINGROUND_CANCELLED_LIST";
export const NSE_D_BOOKINGROUND_ACCIDENT_LIST =
  "NSE_D_BOOKINGROUND_ACCIDENT_LIST";
export const NSE_D_BOOKINGROUND_REVIEW_LIST = "NSE_D_BOOKINGROUND_REVIEW_LIST";
export const NSE_D_BOOKINGROUND_MAXLIMITREACHED_LIST =
  "NSE_D_BOOKINGROUND_MAXLIMITREACHED_LIST";
export const NSE_D_BOOKINGROUND_RETURNTRIP_LIST =
  "NSE_D_BOOKINGROUND_RETURNTRIP_LIST";

export const NSE_D_PAYMENT_FINE_LIST = "NSE_D_PAYMENT_FINE_LIST";
export const NSE_D_PAYMENT_RECEIVED_LIST = "NSE_D_PAYMENT_RECEIVED_LIST";
export const NSE_D_PAYMENT_DUE_LIST = "NSE_D_PAYMENT_DUE_LIST";
export const NSE_D_PAYMENT_DRIVER_CURRENTBALANCE_LIST =
  "NSE_D_PAYMENT_DRIVER_CURRENTBALANCE_LIST";
export const NSE_D_CASHOUT_LIST = "NSE_D_CASHOUT_LIST";

export const NSE_D_EMERSOS_DURINGTRIP_LIST = "NSE_D_EMERSOS_DURINGTRIP_LIST";
export const NSE_D_EMERSOS_NOTRIP_LIST = "NSE_D_EMERSOS_NOTRIP_LIST";
export const NSE_D_EMERSOS_MESSAGING_LIST = "NSE_D_EMERSOS_MESSAGING_LIST";

export const NSE_D_IN_APP_MESS_DURINGTRIP_LIST =
  "NSE_D_IN_APP_MESS_DURINGTRIP_LIST";
export const NSE_D_IN_APP_MESS_COMPLAINT_LIST =
  "NSE_D_IN_APP_MESS_COMPLAINT_LIST";
export const NSE_D_IN_APP_MESS_RESCLOSED_LIST =
  "NSE_D_IN_APP_MESS_RESCLOSED_LIST";

export const NSE_D_INCENTIVE_SLOTSTARTTIME_LIST =
  "NSE_D_INCENTIVE_SLOTSTARTTIME_LIST";
export const NSE_D_INCENTIVE_INPROGRESS_LIST =
  "NSE_D_INCENTIVE_INPROGRESS_LIST";
export const NSE_D_INCENTIVE_SLOTREMAININGTIME_LIST =
  "NSE_D_INCENTIVE_SLOTREMAININGTIME_LIST";
export const NSE_D_INCENTIVE_COMPLETEDSUCCCESS_LIST =
  "NSE_D_INCENTIVE_COMPLETEDSUCCCESS_LIST";

export const NSE_D_FINDONE = "NSE_D_FINDONE";
export const NSE_D_EDIT = "NSE_D_EDIT";

/******* Rider Finance********/

export const RIDER_FINANCE_LIST_FIND_ALL = "RIDER_FINANCE_LIST_FIND_ALL";
export const RIDER_FINANCE_VIEW = "RIDER_FINANCE_VIEW";
export const RIDER_FINANCE_DROPDOWN_LIST = "RIDER_FINANCE_DROPDOWN_LIST";

/******* Driver Finance********/

export const DRFIN_CUR_BAL_LIST = "DRFIN_CUR_BAL_LIST";
export const DRFIN_CUR_BAL_FIND_ONE = "DRFIN_CUR_BAL_FIND_ONE";
export const DRFIN_CREATE_CASH_TRANS_LIST = "DRFIN_CREATE_CASH_TRANS_LIST";
export const DRFIN_CREATE_CASH_TRANS = "DRFIN_CREATE_CASH_TRANS";
export const DRFIN_CREATE_CASH_TRANS_HIST_LIST =
  "DRFIN_CREATE_CASH_TRANS_HIST_LIST";
export const DRFIN_CREATE_CASH_TRANS_HIST_FIND_ONE =
  "DRIVER_FINANCE_CASH_TRANSACTION_HIST_FIND_ONE";
export const DRFIN_CASHOUT_TRANS_HIST_LIST = "DRFIN_CASHOUT_TRANS_HIST_LIST";
export const DRFIN_CASHOUT_TRANS_HIST_FIND_ONE =
  "DRFIN_CASHOUT_TRANS_HIST_FIND_ONE";
export const DRFIN_SUCES_CASH_TRANS_HIST_LIST =
  "DRFIN_SUCES_CASH_TRANS_HIST_LIST";
export const DRFIN_SUCES_CASH_TRANS_HIST_FIND_ONE =
  "DRFIN_SUCES_CASH_TRANS_HIST_FIND_ONE";
export const DRFIN_CUR_BAL_DRP_DWN = "DRFIN_CUR_BAL_DRP_DWN";
export const DRFIN_CREATE_CASH_DRP_DWN = "DRFIN_CREATE_CASH_DRP_DWN";
export const DRFIN_SUCES_CASH_DRP_DWN = "DRFIN_SUCES_CASH_DRP_DWN";
export const DRFIN_CASH_TRANS_DRP_DWN = "DRFIN_CASH_TRANS_DRP_DWN";
export const DRFIN_CASHOUT_TRANS_DRP_DWN = "DRFIN_CASHOUT_TRANS_DRP_DWN";

/************** Driver Metrics ***********/

export const DRIVER_METRICS_LIST = "DRIVER_METRICS_LIST";
export const DRIVER_METRICS_VIEW = "DRIVER_METRICS_VIEW";
export const DRIVER_METRICS_DRP_DWN = "DRIVER_METRICS_DRP_DWN";
export const RIDER_FINANCE_LIST = "RIDER_FINANCE_LIST";
export const RIDER_FINANCE_FIND_ONE = "RIDER_FINANCE_FIND_ONE";

/************** Dfeault Premiums***********/
export const DEFAULT_PREMIUMONE_LIST = "DEFAULT_PREMIUMONE_LIST";
export const DEFAULT_PREMIUMONE_FIND_ONE = "DEFAULT_PREMIUMONE_FIND_ONE";
export const DEFAULT_PREMIUMTWO_FIND_ONE = "DEFAULT_PREMIUMTWO_FIND_ONE";
export const DEFAULT_PREMIUMTHREE_FIND_ONE = "DEFAULT_PREMIUMTHREE_FIND_ONE";
export const DEFAULT_PREMIUMFIVE_FIND_ONE = "DEFAULT_PREMIUMFIVE_FIND_ONE";
export const DEFAULT_PREMIUMSIX_FIND_ONE = "DEFAULT_PREMIUMSIX_FIND_ONE";
export const DEFAULT_PREMIUMFOUR_VIEW = "DEFAULT_PREMIUMFOUR_VIEW";
export const DEFAULT_PREMIUMFOUR_EDIT = "DEFAULT_PREMIUMFOUR_EDIT";
export const MANAGE_PREMIUM_LIST = "MANAGE_PREMIUM_LIST";
export const MANAGE_PREMIUM_RIDE_LIST = "MANAGE_PREMIUM_RIDE_LIST";
export const DEFAULT_PREMIUM_DUEDEPOSIT_FIND_ONE =
  "DEFAULT_PREMIUM_DUEDEPOSIT_FIND_ONE";
export const DEFAULT_PREMIUM_DUEDEPOSIT_EDIT =
  "DEFAULT_PREMIUM_DUEDEPOSIT_EDIT";
export const DEFAULT_PREMIUM1235__EDIT = "DEFAULT_PREMIUM1235__EDIT";
export const MANAGE_PREMIUMONE_FIND_ONE = "MANAGE_PREMIUMONE_FIND_ONE";
export const MANAGE_PREMIUMTWO_FIND_ONE = "MANAGE_PREMIUMTWO_FIND_ONE";
export const MANAGE_PREMIUMTHREE_FIND_ONE = "MANAGE_PREMIUMTHREE_FIND_ONE";
export const MANAGE_PREMIUMFOUR_FIND_ONE = "MANAGE_PREMIUMFOUR_FIND_ONE";
export const MANAGE_PREMIUMFIVE_FIND_ONE = "MANAGE_PREMIUMFIVE_FIND_ONE";
export const MANAGE_PREMIUMSIX_FIND_ONE = "MANAGE_PREMIUMSIX_FIND_ONE";
export const DEFAULT_PREMIUM_PRICING_MODULE_EDIT =
  "DEFAULT_PREMIUM_PRICING_MODULE_EDIT";
export const MANAGE_PREMIUM1235__EDIT = "MANAGE_PREMIUM1235__EDIT";
export const MANAGE_PREMIUM_PRICING_MODULE_EDIT =
  "MANAGE_PREMIUM_PRICING_MODULE_EDIT";
export const MANAGE_PREMIUM_DUEDEPOSIT_EDIT = "MANAGE_PREMIUM_DUEDEPOSIT_EDIT";
export const MANAGE_PREMIUM_DUEDEPOSIT_FIND_ONE =
  "MANAGE_PREMIUM_DUEDEPOSIT_FIND_ONE";
export const MANAGE_PREMIUMFOUR_EDIT = "MANAGE_PREMIUMFOUR_EDIT";
export const MANAGE_PREMIUM_STATUS_UPDATE_EDIT =
  "MANAGE_PREMIUM_STATUS_UPDATE_EDIT";
export const MANAGE_PREMIUM6_STATUS_UPDATE_EDIT =
  "MANAGE_PREMIUM6_STATUS_UPDATE_EDIT";
export const MANAGE_PREMIUM6_DUES_EDIT = "MANAGE_PREMIUM6_DUES_EDIT";
export const MANAGE_PREMIUM4_SUBSCRIPTION = "MANAGE_PREMIUM4_SUBSCRIPTION";
export const MANAGE_PREMIUM5_SUBSCRIPTION = "MANAGE_PREMIUM5_SUBSCRIPTION";
export const MANAGE_PREMIUM6_SUBSCRIPTION = "MANAGE_PREMIUM6_SUBSCRIPTION";
export const UPLOAD_PREMIUM_PIC = "UPLOAD_PREMIUM_PIC";
export const MANAGE_PREMIUM_SUBSCRIPTION_EDIT =
  "MANAGE_PREMIUM_SUBSCRIPTION_EDIT";
export const MANAGE_PREMIUM_SIX_SUBSCRIPTION_EDIT =
  "MANAGE_PREMIUM_SIX_SUBSCRIPTION_EDIT";
export const ARCHIVED_PREMIUMONE_FIND_ONE = "ARCHIVED_PREMIUMONE_FIND_ONE";
export const ARCHIVED_PREMIUMTWO_FIND_ONE = "ARCHIVED_PREMIUMTWO_FIND_ONE";
export const ARCHIVED_PREMIUMTHREE_FIND_ONE = "ARCHIVED_PREMIUMTHREE_FIND_ONE";
export const ARCHIVED_PREMIUMFOUR_FIND_ONE = "ARCHIVED_PREMIUMFOUR_FIND_ONE";
export const ARCHIVED_PREMIUMFIVE_FIND_ONE = "ARCHIVED_PREMIUMFIVE_FIND_ONE";
export const ARCHIVED_PREMIUM_DUEDEPOSIT_FIND_ONE =
  "ARCHIVED_PREMIUM_DUEDEPOSIT_FIND_ONE";
export const ARCHIVED_PREMIUM4_SUBSCRIPTION = "ARCHIVED_PREMIUM4_SUBSCRIPTION";
export const ARCHIVED_PREMIUM5_SUBSCRIPTION = "ARCHIVED_PREMIUM5_SUBSCRIPTION";
export const ARCHIVED_PREMIUM_LIST = "ARCHIVED_PREMIUM_LIST";
export const ARCHIVED_PREMIUM_RIDE_LIST = "ARCHIVED_PREMIUM_RIDE_LIST";

export const PREMIUM_PLAN = "PREMIUM_PLAN";
export const PREMIUM_SCHEDULE_PLAN = "PREMIUM_SCHEDULE_PLAN";
export const PREMIUM_PLAN_SWITCH = "PREMIUM_PLAN_SWITCH";
export const PREMIUM_PLAN_SCHEDULE = "PREMIUM_PLAN_SCHEDULE";
export const PREMIUM_PLAN_CANCEL_SCHEDULE = "PREMIUM_PLAN_CANCEL_SCHEDULE";
export const PREMIUM_PLAN_CANCEL_ACTIVE = "PREMIUM_PLAN_CANCEL_ACTIVE";
export const AUTO_RENEWAL_ACTIVE_INACTIVE_PREMIUM =
  "AUTO_RENEWAL_ACTIVE_INACTIVE_PREMIUM";
export const CANCEL_AUTO_RENEWAL_PREMIUM = "CANCEL_AUTO_RENEWAL_PREMIUM";
export const CANCEL_ACTIVE_AUTO_RENEWAL_PREMIUM =
  "CANCEL_ACTIVE_AUTO_RENEWAL_PREMIUM";
export const CANCEL_ACTIVE_SCHEDULED_PREMIUM =
  "CANCEL_ACTIVE_SCHEDULED_PREMIUM";

// **************** premium - refund *****************

export const PREMIUM_PENDING_REFUND_LIST = "PREMIUM_PENDING_REFUND_LIST";
export const PREMIUM_PENDING_REFUND_VIEW = "PREMIUM_PENDING_REFUND_VIEW";
export const PREMIUM_PENDING_REFUND_UPDATE = "PREMIUM_PENDING_REFUND_UPDATE";
export const PREMIUM_REFUND_CANCEL = "PREMIUM_REFUND_CANCEL";
export const PREMIUM_SUCCESSFUL_REFUND_LIST = "PREMIUM_SUCCESSFUL_REFUND_LIST";
export const PREMIUM_SUCCESSFUL_REFUND_VIEW = "PREMIUM_SUCCESSFUL_REFUND_VIEW";
export const PREMIUM_CANCELLED_REFUND_LIST = "PREMIUM_CANCELLED_REFUND_LIST";
export const PREMIUM_CANCELLED_REFUND_VIEW = "PREMIUM_CANCELLED_REFUND_VIEW";
export const PREMIUM_SUCES_REF_DRP_DWN = "PREMIUM_SUCES_REF_DRP_DWN";
export const PREMIUM_CANCEL_REF_DRP_DWN = "PREMIUM_CANCEL_REF_DRP_DWN";
export const PREMIUM_PEND_REF_DRP_DWN = "PREMIUM_PEND_REF_DRP_DWN";
