import { all } from "redux-saga/effects";
import {
  watchApproveDriverWorker,
  watchBanDriverWorker,
  watchBlockDriverWorker,
  watchDeleteDriverWorker,
  watchDriverListWorker,
  watchDriverPremiumHistoryWorker,
  watchDriverProfileReadWorker,
  watchDriverViewWorker,
  watchRejectDriverWorker,
  watchVehicleModalColorWorker,
  watchbannedDropdownListWorker,
  watchblockeddriverDropdownListWorker,
  watchdelDriverDropdownListWorker,
  watchdriverActivateAutoRenewWorker,
  watchdriverBankDetailsWorker,
  watchdriverCancelActiveAutoRenewWorker,
  watchdriverCancelAutoRenewWorker,
  watchdriverDlWorker,
  watchdriverDropdownListWorker,
  watchdriverPremiumListWorker,
  watchdriverProfileEditWorker,
  watchdriverRCWorker,
  watchdriverVIWorker,
  watchdriverVehicleEditWorker,
  watchdriveraddressProofWorker,
  watchdriverbgverifWorker,
  watchdriverphyverifWorker,
  watchdriverprofilePicWorker,
  watchdrivervehicleImageWorker,
  watchexpiredDropdownListWorker,
  watchpendDropdownListWorker,
  watchperdelDropdownListWorker,
  watchrejdriverDropdownListWorker,
} from "../manageDriversSaga/manageDriversSaga";
import {
  watchpendApplicantBGverifWorker,
  watchpendApplicantDLWorker,
  watchpendApplicantbankdetailsWorker,
  watchpendApplicantprofilePicWorker,
  watchpendBGverifApproveWorker,
  watchpendDLApproveWorker,
  watchpendadressApproveWorker,
  watchpendingApplicantEditWorker,
  watchpendingApplicantPHYverifApproveWorker,
  watchpendingApplicantPHYverifWorker,
  watchpendingApplicantRCApproveWorker,
  watchpendingApplicantRCEditWorker,
  watchpendingApplicantReadWorker,
  watchpendingApplicantVIApproveWorker,
  watchpendingApplicantVIEditWorker,
  watchpendingApplicantVehicleEditWorker,
  watchpendingApplicantVehiclePicApproveWorker,
  watchpendingApplicantVehiclePicWorker,
  watchpendingApplicantViewWorker,
  watchpendingApplicationListWorker,
  watchpendingadressEditWorker,
  watchpendprofilePicApproveWorker,
} from "../manageDriversSaga/pendingApplicantSaga";
import {
  watchuploadAdressWorker,
  watchuploadBGverifWorker,
  watchuploadDLWorker,
  watchuploadInsuranceWorker,
  watchuploadPhyVerifPicWorker,
  watchuploadRCWorker,
  watchuploadVehiclePicWorker,
  watchuploadprofilePicWorker,
} from "../imageUploadSaga";
import {
  watchrejectApplicantVIWorker,
  watchrejectApplicantaddressProofWorker,
  watchrejectApplicantprofilePicWorker,
  watchrejectApplicantvehicleImageWorker,
  watchrejectApplicatantDlWorker,
  watchrejectApplicatantRCWorker,
  watchrejectApplicationReadWorker,
  watchrejectapplicantBankDetailsWorker,
  watchrejectapplicantbgverifWorker,
  watchrejectapplicantphyverifWorker,
  watchrejectedApplicationListWorker,
  watchrejectedApplicationViewWorker,
} from "../manageDriversSaga/rejectedApplicantSaga";
import {
  watchUnblockDriverWorker,
  watchblockedApplicantReadWorker,
  watchblockedApplicantVIWorker,
  watchblockedApplicantaddressProofWorker,
  watchblockedApplicantprofilePicWorker,
  watchblockedApplicantvehicleImageWorker,
  watchblockedApplicatantDlWorker,
  watchblockedApplicatantRCWorker,
  watchblockedApplicationListWorker,
  watchblockedApplicationViewWorker,
  watchblockedapplicantbgverifWorker,
  watchblockedapplicantphyverifWorker,
} from "../manageDriversSaga/blockedApplicantSaga";
import {
  watchbannedApplicationListWorker,
  watchbannedApplicationReadWorker,
  watchbannedApplicationViewWorker,
} from "../manageDriversSaga/bannedApplicantSaga";
import {
  watchexpiredDocumentListWorker,
  watchexpiredDocumentViewWorker,
  watchexpireddcoumentBankDetailsWorker,
  watchexpireddocumentDlWorker,
  watchexpireddocumentRCWorker,
  watchexpireddocumentVIWorker,
  watchexpireddocumentaddressProofWorker,
  watchexpireddocumentbgverifWorker,
  watchexpireddocumentphyverifWorker,
  watchexpireddocumentprofilePicWorker,
  watchexpireddocumentvehicleImageWorker,
  watchexpiredprofileReadWorker,
} from "../manageDriversSaga/expiredDocumentSaga";
import {
  watchDeletedDriverListWorker,
  watchDeletedDriverReadWorker,
  watchDeletedDriverViewWorker,
  watchPerDeletedDriverWorker,
  watchRestoreDriverWorker,
  watchperDeletedDriverListWorker,
  watchperDeletedDriverReadWorker,
  watchperDeletedDriverViewWorker,
} from "../manageDriversSaga/deleteDriverSaga";
import {
  watchManageDriverMainZoneListWorker,
  watchManageDriverRideTypeListWorker,
  watchManageDriverVehicleColorListWorker,
  watchManageDriverVehicleTypeListWorker,
} from "../manageDriversSaga/dropDownListSaga";
import {
  WatchSendDriveromplaintMessagesWorker,
  WatchSendDriverSosMessagesWorker,
  WatchSendRiderComplaintMessagesWorker,
} from "../chatSectionSaga/chatSectionSaga";

export default function* manageDriverRootSaga() {
  yield all([
    watchdelDriverDropdownListWorker(),
    watchdriverDropdownListWorker(),
    watchpendDropdownListWorker(),
    watchblockeddriverDropdownListWorker(),
    watchbannedDropdownListWorker(),
    watchexpiredDropdownListWorker(),
    watchrejdriverDropdownListWorker(),
    watchdelDriverDropdownListWorker(),
    watchperdelDropdownListWorker(),
    watchDriverListWorker(),
    watchDriverViewWorker(),
    watchDriverPremiumHistoryWorker(),
    watchDriverProfileReadWorker(),
    watchBanDriverWorker(),
    watchDeleteDriverWorker(),
    watchBlockDriverWorker(),
    watchdriverProfileEditWorker(),

    watchdriverVehicleEditWorker(),
    watchpendingadressEditWorker(),
    watchpendadressApproveWorker(),
    watchpendingApplicationListWorker(),
    watchpendingApplicantViewWorker(),
    watchpendingApplicantReadWorker(),
    watchpendingApplicantEditWorker(),
    watchpendingApplicantVehicleEditWorker(),
    watchpendApplicantbankdetailsWorker(),
    watchuploadAdressWorker(),
    watchuploadDLWorker(),
    watchpendDLApproveWorker(),
    watchpendApplicantDLWorker(),
    watchuploadInsuranceWorker(),
    watchpendApplicantprofilePicWorker(),
    watchuploadprofilePicWorker(),
    watchpendprofilePicApproveWorker(),
    watchpendApplicantBGverifWorker(),
    watchuploadBGverifWorker(),
    watchpendBGverifApproveWorker(),
    watchpendingApplicantVIApproveWorker(),
    watchpendingApplicantVIEditWorker(),
    watchrejectedApplicationListWorker(),
    watchrejectedApplicationViewWorker(),
    watchblockedApplicationListWorker(),
    watchblockedApplicationViewWorker(),
    watchblockedApplicantReadWorker(),
    watchUnblockDriverWorker(),
    watchblockedApplicantaddressProofWorker(),
    watchblockedApplicatantDlWorker(),
    watchblockedApplicantprofilePicWorker(),
    watchblockedapplicantbgverifWorker(),
    watchblockedApplicantVIWorker(),
    watchblockedApplicatantRCWorker(),
    watchblockedApplicantvehicleImageWorker(),
    watchblockedapplicantphyverifWorker(),
    watchuploadRCWorker(),
    watchpendingApplicantRCEditWorker(),
    watchpendingApplicantRCApproveWorker(),
    watchbannedApplicationListWorker(),
    watchpendingApplicantVehiclePicWorker(),
    watchpendingApplicantVehiclePicApproveWorker(),
    watchuploadVehiclePicWorker(),
    watchbannedApplicationViewWorker(),
    watchbannedApplicationReadWorker(),
    watchpendingApplicantPHYverifWorker(),
    watchpendingApplicantPHYverifApproveWorker(),
    watchuploadPhyVerifPicWorker(),
    watchApproveDriverWorker(),
    watchRejectDriverWorker(),
    watchrejectApplicationReadWorker(),
    watchrejectapplicantBankDetailsWorker(),
    watchrejectApplicantaddressProofWorker(),
    watchrejectApplicatantDlWorker(),
    watchrejectApplicantprofilePicWorker(),
    watchrejectapplicantbgverifWorker(),
    watchrejectApplicantVIWorker(),
    watchrejectApplicatantRCWorker(),
    watchrejectApplicantvehicleImageWorker(),
    watchrejectapplicantphyverifWorker(),

    watchexpiredDocumentListWorker(),
    watchexpiredDocumentViewWorker(),
    watchdriverBankDetailsWorker(),
    watchdriveraddressProofWorker(),
    watchdriverDlWorker(),
    watchdriverprofilePicWorker(),
    watchdriverbgverifWorker(),
    watchdriverVIWorker(),
    watchdriverRCWorker(),
    watchdrivervehicleImageWorker(),
    watchdriverphyverifWorker(),
    watchdriverPremiumListWorker(),
    watchdriverActivateAutoRenewWorker(),
    watchdriverCancelAutoRenewWorker(),
    watchdriverCancelActiveAutoRenewWorker(),
    watchexpireddcoumentBankDetailsWorker(),
    watchexpireddocumentDlWorker(),
    watchexpireddocumentaddressProofWorker(),
    watchexpireddocumentDlWorker(),
    watchexpireddocumentprofilePicWorker(),
    watchexpireddocumentbgverifWorker(),
    watchexpireddocumentVIWorker(),
    watchexpireddocumentRCWorker(),
    watchexpireddocumentvehicleImageWorker(),
    watchexpireddocumentphyverifWorker(),
    watchexpiredprofileReadWorker(),
    watchDeletedDriverListWorker(),
    watchDeletedDriverViewWorker(),
    watchDeletedDriverReadWorker(),
    watchRestoreDriverWorker(),
    watchPerDeletedDriverWorker(),
    watchperDeletedDriverListWorker(),
    watchperDeletedDriverViewWorker(),
    watchperDeletedDriverReadWorker(),
    watchManageDriverMainZoneListWorker(),
    watchManageDriverVehicleColorListWorker(),
    watchManageDriverRideTypeListWorker(),
    watchManageDriverVehicleTypeListWorker(),
    watchVehicleModalColorWorker(),
    WatchSendDriverSosMessagesWorker(),
    WatchSendDriveromplaintMessagesWorker(),
    WatchSendRiderComplaintMessagesWorker(),
  ]);
}
